import { useState } from "react";
import { Search } from "lucide-react";
import { AutoComplete, Button, Cascader, Checkbox, ColorPicker, DatePicker, DateRangePicker, Field, Form, Input, InputNumber, InputOTP, Mentions, Radio, Rate, Segmented, Select, Slider, Space, Switch, Text, Textarea, TimePicker, Transfer, TreeSelect, Upload } from "../../../src/core";
import type { ComponentDocument } from "../../components/component-page";

function ControlledSelectDemo() {
  const [value, setValue] = useState("design");
  return <Space direction="vertical"><Select value={value} onChange={(event) => setValue(event.target.value)}><option value="design">设计</option><option value="engineering">工程</option><option value="product">产品</option></Select><Text tone="muted">当前值：{value}</Text></Space>;
}

function ControlledInputDemo() {
  const [value, setValue] = useState("Gouno UI");
  return <Space direction="vertical"><Input value={value} allowClear prefix={<Search />} onChange={(event) => setValue(event.target.value)} onClear={() => setValue("")} /><Text tone="muted">当前值：{value || "（空）"}</Text></Space>;
}

function ControlledTextareaDemo() {
  const [value, setValue] = useState("组件 API、示例和代码应保持一致。");
  return <Textarea value={value} maxLength={60} showCount onChange={(event) => setValue(event.target.value)} />;
}

function ControlledInputNumberDemo() {
  const [value, setValue] = useState<number | null>(1280);
  return <Space direction="vertical"><InputNumber value={value} min={0} step={100} precision={2} formatter={(number) => number === null ? "" : `¥ ${number}`} parser={(display) => Number(display.replace(/[^0-9.-]/g, ""))} onChange={setValue} /><Text tone="muted">数值：{value ?? "空"}</Text></Space>;
}

function ControlledDatePickerDemo() {
  const [value, setValue] = useState("2026-09-06");
  return <Space direction="vertical"><DatePicker value={value} allowClear onChange={setValue} /><Text tone="muted">日期：{value || "未选择"}</Text></Space>;
}

function ControlledUploadDemo() {
  const [files, setFiles] = useState<File[]>([]);
  return <Upload files={files} multiple maxCount={2} maxSize={1024 * 1024} accept="image/*" drag onFiles={setFiles}>拖放图片或点击选择，最多 2 张</Upload>;
}

function FormValidationDemo() {
  const [message, setMessage] = useState("尚未提交");
  return <Form onFinish={(_formData, values) => setMessage(`已提交：${values.siteName}`)} onFinishFailed={() => setMessage("请检查必填字段")}><Field label="站点名称" hint="显示在浏览器标题中" required><Input name="siteName" defaultValue="Gouno" /></Field><Field label="联系邮箱" required><Input name="email" type="email" placeholder="name@example.com" /></Field><Button type="submit" variant="primary">校验并提交</Button><Text tone="muted" aria-live="polite">{message}</Text></Form>;
}
export const dataEntryDocuments: Record<string, ComponentDocument> = {
  "input-number": { title: "InputNumber 数字输入", description: "支持边界、步长、精度、格式化、受控状态和键盘操作。", code: '<InputNumber aria-label="数量" min={0} max={10} defaultValue={3} />', render: () => <InputNumber aria-label="数量" min={0} max={10} defaultValue={3} />, demos: [{ title: "尺寸与状态", code: '<Space direction="vertical">\n  <InputNumber size="small" defaultValue={1} />\n  <InputNumber size="middle" defaultValue={2} status="warning" />\n  <InputNumber size="large" defaultValue={3} status="error" />\n  <InputNumber defaultValue={4} readOnly />\n  <InputNumber defaultValue={5} disabled />\n</Space>', render: () => <Space direction="vertical"><InputNumber size="small" defaultValue={1} /><InputNumber size="middle" defaultValue={2} status="warning" /><InputNumber size="large" defaultValue={3} status="error" /><InputNumber defaultValue={4} readOnly /><InputNumber defaultValue={5} disabled /></Space> }, { title: "受控、格式化与精度", description: "按钮和方向键使用相同的步进、边界与精度规则。", code: 'function ControlledInputNumberDemo() {\n  const [value, setValue] = useState<number | null>(1280);\n  return <Space direction="vertical"><InputNumber value={value} min={0} step={100} precision={2} formatter={(number) => number === null ? "" : `¥ ${number}`} parser={(display) => Number(display.replace(/[^0-9.-]/g, ""))} onChange={setValue} /><Text tone="muted">数值：{value ?? "空"}</Text></Space>;\n}', render: () => <ControlledInputNumberDemo /> }], api: [{ name: "value / defaultValue", description: "受控或非受控数值", type: "number | null" }, { name: "min / max / step / precision", description: "边界、步长和小数精度", type: "number" }, { name: "formatter / parser", description: "显示值和数值转换", type: "functions" }, { name: "controls / keyboard", description: "启用步进按钮和方向键", type: "boolean", defaultValue: "true" }, { name: "onStep", description: "步进完成回调", type: "(value, info) => void" }] },
  "date-picker": { title: "DatePicker 日期选择", description: "使用浏览器原生日期能力，提供统一尺寸、状态、受控值和清除操作。", code: '<DatePicker aria-label="发布日期" defaultValue="2026-09-06" />', render: () => <DatePicker aria-label="发布日期" defaultValue="2026-09-06" />, demos: [{ title: "尺寸、边界与状态", code: '<Space direction="vertical">\n  <DatePicker size="small" min="2026-01-01" max="2026-12-31" />\n  <DatePicker size="middle" status="warning" />\n  <DatePicker size="large" status="error" />\n  <DatePicker defaultValue="2026-09-06" readOnly />\n  <DatePicker disabled />\n</Space>', render: () => <Space direction="vertical"><DatePicker size="small" min="2026-01-01" max="2026-12-31" /><DatePicker size="middle" status="warning" /><DatePicker size="large" status="error" /><DatePicker defaultValue="2026-09-06" readOnly /><DatePicker disabled /></Space> }, { title: "受控与清除", code: 'function ControlledDatePickerDemo() {\n  const [value, setValue] = useState("2026-09-06");\n  return <Space direction="vertical"><DatePicker value={value} allowClear onChange={setValue} /><Text tone="muted">日期：{value || "未选择"}</Text></Space>;\n}', render: () => <ControlledDatePickerDemo /> }], api: [{ name: "value / defaultValue", description: "ISO 日期字符串", type: "string" }, { name: "min / max", description: "可选日期边界", type: "string" }, { name: "size", description: "控件尺寸", type: '"small" | "middle" | "large"' }, { name: "status", description: "校验状态", type: '"error" | "warning"' }, { name: "allowClear", description: "显示清除按钮", type: "boolean", defaultValue: "true" }, { name: "onChange", description: "返回字符串和 Date", type: "(value, date) => void" }] },
  "date-range-picker": { title:"DateRangePicker 日期范围", description:"受控开始和结束日期。", code:'<DateRangePicker start={start} end={end} onChange={setRange} />', render:()=> <DateRangePicker start="2026-09-01" end="2026-09-06" onChange={()=>undefined}/> },
  "time-picker": { title: "TimePicker 时间选择", description: "原生时间输入和键盘操作。", code: '<TimePicker aria-label="发布时间" />', render: () => <TimePicker aria-label="发布时间" /> },
  "color-picker": { title: "ColorPicker 颜色选择", description: "浏览器原生颜色选择。", code: '<ColorPicker defaultValue="#1677ff" />', render: () => <ColorPicker aria-label="品牌色" defaultValue="#1677ff" /> },
  upload: { title: "Upload 上传", description: "提供文件选择、拖放、受控列表、类型/大小/数量校验和逐项移除。", code: '<Upload accept="image/*" multiple maxCount={3}>选择图片</Upload>', render: () => <Upload accept="image/*" multiple maxCount={3}>选择图片</Upload>, demos: [{ title: "受控拖放区域", code: 'function ControlledUploadDemo() {\n  const [files, setFiles] = useState<File[]>([]);\n  return <Upload files={files} multiple maxCount={2} maxSize={1024 * 1024} accept="image/*" drag onFiles={setFiles}>拖放图片或点击选择，最多 2 张</Upload>;\n}', render: () => <ControlledUploadDemo /> }, { title: "文件列表与移除", code: '<Upload defaultFiles={[new File(["demo"], "cover.png", { type: "image/png" })]}>替换文件</Upload>', render: () => <Upload defaultFiles={[new File(["demo"], "cover.png", { type: "image/png" })]}>替换文件</Upload> }, { title: "禁用与错误", code: '<Space direction="vertical">\n  <Upload disabled>禁止上传</Upload>\n  <Upload error="文件超过 5 MB，请压缩后重试。">重新选择</Upload>\n</Space>', render: () => <Space direction="vertical"><Upload disabled>禁止上传</Upload><Upload error="文件超过 5 MB，请压缩后重试。">重新选择</Upload></Space> }], api: [{ name: "files / defaultFiles", description: "受控或非受控文件列表", type: "File[]" }, { name: "onFiles / onRemove", description: "文件列表和移除回调", type: "functions" }, { name: "accept / multiple", description: "类型和多选约束", type: "native attributes" }, { name: "maxCount / maxSize", description: "数量和单文件大小限制", type: "number" }, { name: "beforeSelect / onReject", description: "选择前检查和拒绝原因", type: "functions" }, { name: "drag", description: "启用拖放区域", type: "boolean", defaultValue: "false" }] },
  input: { title: "Input 输入框", description: "文本输入、前后插槽、三种尺寸、清除、校验状态和原生表单能力。", code: '<Input placeholder="请输入内容" />', render: () => <Input placeholder="请输入内容" />, demos: [{ title: "尺寸、插槽与状态", code: '<Space direction="vertical">\n  <Input size="small" prefix={<Search />} placeholder="Small" />\n  <Input size="middle" suffix=".com" placeholder="Middle" />\n  <Input size="large" placeholder="Large" />\n  <Input status="warning" defaultValue="需要确认" />\n  <Input status="error" defaultValue="格式错误" />\n  <Input readOnly value="只读内容" />\n  <Input disabled value="禁用内容" />\n</Space>', render: () => <Space direction="vertical"><Input size="small" prefix={<Search />} placeholder="Small" /><Input size="middle" suffix=".com" placeholder="Middle" /><Input size="large" placeholder="Large" /><Input status="warning" defaultValue="需要确认" /><Input status="error" defaultValue="格式错误" /><Input readOnly value="只读内容" /><Input disabled value="禁用内容" /></Space> }, { title: "受控与清除", code: 'function ControlledInputDemo() {\n  const [value, setValue] = useState("Gouno UI");\n  return <Space direction="vertical"><Input value={value} allowClear prefix={<Search />} onChange={(event) => setValue(event.target.value)} onClear={() => setValue("")} /><Text tone="muted">当前值：{value || "（空）"}</Text></Space>;\n}', render: () => <ControlledInputDemo /> }], api: [{ name: "value / defaultValue", description: "受控或非受控文本", type: "string" }, { name: "size", description: "控件尺寸", type: '"small" | "middle" | "large"' }, { name: "prefix / suffix", description: "前后内容插槽", type: "ReactNode" }, { name: "allowClear / onClear", description: "清除操作", type: "boolean / function" }, { name: "status", description: "校验状态", type: '"error" | "warning"' }] },
  textarea: { title: "Textarea 多行输入", description: "提供三种尺寸、字符计数、受控值和校验状态。", code: '<Textarea rows={4} placeholder="请输入内容" />', render: () => <Textarea rows={4} placeholder="请输入内容" />, demos: [{ title: "字符计数与受控值", code: 'function ControlledTextareaDemo() {\n  const [value, setValue] = useState("组件 API、示例和代码应保持一致。");\n  return <Textarea value={value} maxLength={60} showCount onChange={(event) => setValue(event.target.value)} />;\n}', render: () => <ControlledTextareaDemo /> }, { title: "尺寸与状态", code: '<Space direction="vertical">\n  <Textarea size="small" placeholder="Small" />\n  <Textarea size="large" placeholder="Large" />\n  <Textarea status="warning" defaultValue="需要确认" />\n  <Textarea status="error" defaultValue="格式错误" />\n  <Textarea readOnly value="只读内容" />\n  <Textarea disabled value="禁用内容" />\n</Space>', render: () => <Space direction="vertical"><Textarea size="small" placeholder="Small" /><Textarea size="large" placeholder="Large" /><Textarea status="warning" defaultValue="需要确认" /><Textarea status="error" defaultValue="格式错误" /><Textarea readOnly value="只读内容" /><Textarea disabled value="禁用内容" /></Space> }], api: [{ name: "value / defaultValue", description: "受控或非受控文本", type: "string" }, { name: "showCount", description: "显示可访问字符计数", type: "boolean" }, { name: "maxLength", description: "最大字符数", type: "number" }, { name: "size", description: "控件尺寸", type: '"small" | "middle" | "large"' }, { name: "status", description: "校验状态", type: '"error" | "warning"' }] },
  select: { title: "Select 选择器", description: "以原生选择器保留完整键盘操作、表单序列化和移动端选择体验。", code: '<Select defaultValue="a"><option value="a">选项一</option><option value="b">选项二</option></Select>', render: () => <Select defaultValue="a"><option value="a">选项一</option><option value="b">选项二</option></Select>, demos: [{ title: "尺寸与状态", code: '<Space direction="vertical">\n  <Select size="small" placeholder="请选择"><option value="a">Small</option></Select>\n  <Select size="middle" status="warning" defaultValue="a"><option value="a">Warning</option></Select>\n  <Select size="large" status="error" defaultValue="a"><option value="a">Error</option></Select>\n  <Select loading><option>加载中</option></Select>\n  <Select disabled><option>禁用</option></Select>\n</Space>', render: () => <Space direction="vertical"><Select size="small" placeholder="请选择"><option value="a">Small</option></Select><Select size="middle" status="warning" defaultValue="a"><option value="a">Warning</option></Select><Select size="large" status="error" defaultValue="a"><option value="a">Error</option></Select><Select loading><option>加载中</option></Select><Select disabled><option>禁用</option></Select></Space> }, { title: "受控模式", code: 'function ControlledSelectDemo() {\n  const [value, setValue] = useState("design");\n  return <Space direction="vertical"><Select value={value} onChange={(event) => setValue(event.target.value)}><option value="design">设计</option><option value="engineering">工程</option><option value="product">产品</option></Select><Text tone="muted">当前值：{value}</Text></Space>;\n}', render: () => <ControlledSelectDemo /> }], api: [{ name: "value / defaultValue", description: "受控或非受控选项", type: "string | string[]" }, { name: "placeholder", description: "空值提示选项", type: "string" }, { name: "size", description: "控件尺寸", type: '"small" | "middle" | "large"' }, { name: "status", description: "校验状态", type: '"error" | "warning"' }, { name: "loading", description: "忙碌并禁止交互", type: "boolean" }] },
  checkbox: { title: "Checkbox 多选框", description: "独立选择和禁用状态。", code: '<Checkbox label="接受条款" />', render: () => <Space direction="vertical"><Checkbox label="接受条款" defaultChecked /><Checkbox label="禁用选项" disabled /></Space> },
  radio: { title: "Radio 单选框", description: "使用相同 name 组成单选组。", code: '<Radio name="plan" label="基础版" />', render: () => <Space><Radio name="plan" label="基础版" defaultChecked /><Radio name="plan" label="专业版" /></Space> },
  switch: { title: "Switch 开关", description: "即时切换布尔状态。", code: '<Switch label="启用通知" />', render: () => <Space direction="vertical"><Switch label="启用通知" defaultChecked /><Switch label="禁用" disabled /></Space> },
  slider: { title: "Slider 滑动输入", description: "范围、步长、禁用和键盘调整。", code: '<Slider min={0} max={100} defaultValue={40} />', render: () => <div className="max-w-md"><Slider aria-label="音量" min={0} max={100} defaultValue={40} /></div> },
  rate: { title: "Rate 评分", description: "受控或非受控星级评分。", code: '<Rate defaultValue={3} />', render: () => <Rate defaultValue={3} /> },
  autocomplete: { title: "AutoComplete 自动完成", description: "输入过滤和可访问列表框。", code: '<AutoComplete options={["Beijing", "Shanghai"]} />', render: () => <div className="max-w-sm"><AutoComplete placeholder="输入城市" options={["Beijing", "Shanghai", "Shenzhen", "Hangzhou"]} /></div> },
  segmented: { title: "Segmented 分段控制", description: "在少量互斥选项之间切换。", code: '<Segmented options={["日", "周", "月"]} />', render: () => <Segmented options={["日", "周", "月"]} defaultValue="周" /> },
  cascader: { title: "Cascader 级联选择", description: "从层级数据中逐级选择。", code: '<Cascader options={regions} onChange={setValue} />', render: () => <Cascader options={[{ value:"zhejiang", label:"浙江", children:[{ value:"hangzhou", label:"杭州" },{ value:"ningbo", label:"宁波" }]},{ value:"jiangsu", label:"江苏", children:[{ value:"nanjing", label:"南京" }]}]} /> },
  "tree-select": { title: "TreeSelect 树选择", description: "从树形数据中选择一个或多个节点。", code: '<TreeSelect treeData={nodes} />', render: () => <TreeSelect treeData={[{ value:"docs", title:"文档", children:[{ value:"api", title:"API" },{ value:"guide", title:"指南" }]}]} defaultValue="api" /> },
  transfer: { title: "Transfer 穿梭框", description: "在两个集合间移动和选择条目。", code: '<Transfer dataSource={items} defaultTargetKeys={["2"]} />', render: () => <Transfer dataSource={[{key:"1",title:"成员一"},{key:"2",title:"成员二"},{key:"3",title:"成员三"}]} defaultTargetKeys={["2"]} titles={["可选成员","已选择"]} /> },
  mentions: { title: "Mentions 提及", description: "输入 @ 时显示匹配建议。", code: '<Mentions options={["alice", "bob"]} />', render: () => <Mentions aria-label="评论" placeholder="输入 @ 提及成员" options={["alice","bob","charlie"]} /> },
  "input-otp": { title:"Input.OTP 验证码输入", description:"自动跳格、退格回退和一次性密码自动填充。", code:'<InputOTP length={6} onChange={setCode} />', render:()=> <InputOTP length={6} /> },
  form: { title:"Form 表单", description:"原生表单语义之上提供字段关联、校验结果、提交值、三种布局和整体状态。", code:'<Form><Field label="站点名称" hint="显示在页面标题中" required><Input name="siteName" /></Field><Button type="submit">提交</Button></Form>', render:()=> <Form><Field label="站点名称" hint="显示在页面标题中" required><Input name="siteName" /></Field><Button type="submit">提交</Button></Form>, demos: [{ title: "校验与提交", description: "原生约束失败触发 onFinishFailed；成功时同时返回 FormData 和解析后的 values。", code: 'function FormValidationDemo() {\n  const [message, setMessage] = useState("尚未提交");\n  return <Form onFinish={(_formData, values) => setMessage(`已提交：${values.siteName}`)} onFinishFailed={() => setMessage("请检查必填字段")}><Field label="站点名称" hint="显示在浏览器标题中" required><Input name="siteName" defaultValue="Gouno" /></Field><Field label="联系邮箱" required><Input name="email" type="email" placeholder="name@example.com" /></Field><Button type="submit" variant="primary">校验并提交</Button><Text tone="muted" aria-live="polite">{message}</Text></Form>;\n}', render: () => <FormValidationDemo /> }, { title: "水平与行内布局", code: '<Space direction="vertical">\n  <Form layout="horizontal"><Field label="站点名称"><Input defaultValue="Gouno UI" /></Field><Button>保存</Button></Form>\n  <Form layout="inline"><Field label="关键词"><Input placeholder="搜索" /></Field><Button>查询</Button></Form>\n</Space>', render: () => <Space direction="vertical"><Form layout="horizontal"><Field label="站点名称"><Input defaultValue="Gouno UI" /></Field><Button>保存</Button></Form><Form layout="inline"><Field label="关键词"><Input placeholder="搜索" /></Field><Button>查询</Button></Form></Space> }, { title: "禁用与加载", code: '<Space direction="vertical">\n  <Form disabled><Field label="禁用字段"><Input value="不可编辑" readOnly /></Field><Button>提交</Button></Form>\n  <Form loading><Field label="加载字段"><Input value="提交中" readOnly /></Field><Button>提交中</Button></Form>\n</Space>', render: () => <Space direction="vertical"><Form disabled><Field label="禁用字段"><Input value="不可编辑" readOnly /></Field><Button>提交</Button></Form><Form loading><Field label="加载字段"><Input value="提交中" readOnly /></Field><Button>提交中</Button></Form></Space> }], api: [{ name: "layout", description: "表单布局", type: '"vertical" | "horizontal" | "inline"', defaultValue: '"vertical"' }, { name: "disabled / loading", description: "整体禁用与提交状态", type: "boolean" }, { name: "onFinish", description: "首参 FormData，次参解析后的 values", type: "(formData, values) => void" }, { name: "onFinishFailed", description: "原生约束校验失败回调", type: "(event) => void" }, { name: "Field error / hint", description: "错误与帮助信息关联", type: "ReactNode" }] }
};
