import { useState } from "react";
import { Search } from "lucide-react";
import { AutoComplete, Button, Cascader, Checkbox, ColorPicker, DatePicker, DateRangePicker, Field, Form, Input, InputNumber, InputOTP, Mentions, Radio, Rate, Segmented, Select, Slider, Space, Switch, Text, Textarea, TimePicker, Transfer, TreeSelect, Upload } from "../../../src/core";
import type { ComponentDocument } from "../../components/component-page";

function ControlledInputDemo() { const [value, setValue] = useState("Gouno UI"); return <Space direction="vertical"><Input value={value} allowClear prefix={<Search />} onChange={e => setValue(e.target.value)} onClear={() => setValue("")} /><Text tone="muted">当前值：{value || "（空）"}</Text></Space>; }
function ControlledTextareaDemo() { const [value, setValue] = useState("组件 API、示例和代码应保持一致。"); return <Textarea value={value} maxLength={60} showCount onChange={e => setValue(e.target.value)} />; }
function ControlledSelectDemo() { const [value, setValue] = useState("design"); return <Space direction="vertical"><Select value={value} onChange={e => setValue(e.target.value)}><option value="design">设计</option><option value="engineering">工程</option><option value="product">产品</option></Select><Text tone="muted">当前值：{value}</Text></Space>; }
function ControlledInputNumberDemo() { const [value, setValue] = useState<number | null>(1280); return <Space direction="vertical"><InputNumber value={value} min={0} step={100} precision={2} formatter={n => n === null ? "" : `¥ ${n}`} parser={s => Number(s.replace(/[^0-9.-]/g, ""))} onChange={setValue} /><Text tone="muted">数值：{value ?? "空"}</Text></Space>; }
function ControlledDatePickerDemo() { const [value, setValue] = useState("2026-09-06"); return <Space direction="vertical"><DatePicker value={value} allowClear onChange={setValue} /><Text tone="muted">日期：{value || "未选择"}</Text></Space>; }
function ControlledUploadDemo() { const [files, setFiles] = useState<File[]>([]); return <Upload files={files} multiple maxCount={2} maxSize={1024 * 1024} accept="image/*" drag onFiles={setFiles}>拖放图片或点击选择，最多 2 张</Upload>; }
function FormValidationDemo() { const [message, setMessage] = useState("尚未提交"); return <Form onFinish={(_data, values) => setMessage(`已提交：${values.siteName}`)} onFinishFailed={() => setMessage("请检查必填字段")}><Field label="站点名称" required><Input name="siteName" defaultValue="Gouno" /></Field><Field label="联系邮箱" required><Input name="email" type="email" /></Field><Button type="submit" variant="primary">校验并提交</Button><Text tone="muted" aria-live="polite">{message}</Text></Form>; }

const api = {
  input: [{ name: "value / defaultValue", description: "受控或非受控文本", type: "string" }, { name: "size / prefix / suffix", description: "尺寸和插槽", type: "Size / ReactNode" }, { name: "allowClear / onClear", description: "清除操作", type: "boolean / function" }, { name: "status / disabled / readOnly", description: "状态", type: "Status / boolean" }, { name: "name / id / placeholder / onChange / ref / className", description: "原生属性、事件、引用和样式", type: "string / function / Ref" }],
  textarea: [{ name: "value / defaultValue", description: "受控或非受控文本", type: "string" }, { name: "showCount / maxLength", description: "字符计数和最大长度", type: "boolean / number" }, { name: "size / status", description: "尺寸和校验状态", type: "Size / Status" }, { name: "rows / cols / disabled / readOnly", description: "原生尺寸和状态", type: "number / boolean" }, { name: "name / id / placeholder / onChange / ref / className", description: "原生属性、事件、引用和样式", type: "string / function / Ref" }],
  select: [{ name: "children", description: "option/optgroup 组合", type: "ReactNode" }, { name: "value / defaultValue", description: "受控或非受控选项", type: "string | string[]" }, { name: "placeholder / size / status", description: "提示、尺寸和校验状态", type: "string / Size / Status" }, { name: "loading / disabled / multiple", description: "交互状态和多选", type: "boolean" }, { name: "name / id / required / onChange / ref / className", description: "原生属性、事件、引用和样式", type: "string / boolean / function" }],
  form: [{ name: "children", description: "Field、控件和操作按钮", type: "ReactNode" }, { name: "layout", description: "表单布局", type: '"vertical" | "horizontal" | "inline"' }, { name: "disabled / loading", description: "整体禁用和提交状态", type: "boolean" }, { name: "onFinish / onFinishFailed", description: "成功提交 FormData、values，失败回调", type: "functions" }, { name: "validateMessages / name / method / className", description: "校验文案和原生属性", type: "object / string" }],
  "input-number": [{ name: "value / defaultValue / min / max / step / precision", description: "数值状态、边界、步长和精度", type: "number | null" }, { name: "formatter / parser", description: "显示值和数值转换", type: "functions" }, { name: "controls / keyboard / onStep", description: "步进按钮、方向键和回调", type: "boolean / function" }],
  "date-picker": [{ name: "value / defaultValue / min / max", description: "受控值和日期边界", type: "string" }, { name: "size / status / allowClear", description: "尺寸、校验状态和清除", type: "Size / Status / boolean" }, { name: "disabled / readOnly / onChange / ref", description: "状态、事件和引用", type: "boolean / function / Ref" }],
  upload: [{ name: "files / defaultFiles", description: "受控或非受控文件列表", type: "File[]" }, { name: "onFiles / onRemove", description: "文件列表和移除回调", type: "functions" }, { name: "accept / multiple / maxCount / maxSize", description: "文件约束", type: "string / boolean / number" }, { name: "beforeSelect / onReject / drag / disabled / error", description: "校验、拖放和状态", type: "functions / boolean / string" }],
};

export const dataEntryDocuments: Record<string, ComponentDocument> = {
  input: { title: "Input 输入框", description: "文本输入、插槽、尺寸、清除、校验和原生表单能力。", code: '<Input placeholder="请输入内容" />', render: () => <Input placeholder="请输入内容" />, demos: [{ title: "尺寸、插槽与状态", code: '<Space direction="vertical"><Input size="small" prefix={<Search />} placeholder="Small" /><Input size="middle" suffix=".com" placeholder="Middle" /><Input size="large" placeholder="Large" /><Input status="warning" defaultValue="需要确认" /><Input status="error" defaultValue="格式错误" /><Input readOnly value="只读内容" /><Input disabled value="禁用内容" /></Space>', render: () => <Space direction="vertical"><Input size="small" prefix={<Search />} placeholder="Small" /><Input size="middle" suffix=".com" placeholder="Middle" /><Input size="large" placeholder="Large" /><Input status="warning" defaultValue="需要确认" /><Input status="error" defaultValue="格式错误" /><Input readOnly value="只读内容" /><Input disabled value="禁用内容" /></Space> }, { title: "受控与清除", code: 'const [value, setValue] = useState("Gouno UI");\n<Input value={value} allowClear onChange={event => setValue(event.target.value)} onClear={() => setValue("")} />', render: () => <ControlledInputDemo /> }], api: api.input },
  textarea: { title: "Textarea 多行输入", description: "尺寸、字符计数、受控值和校验状态。", code: '<Textarea rows={4} placeholder="请输入内容" />', render: () => <Textarea rows={4} placeholder="请输入内容" />, demos: [{ title: "字符计数与受控值", code: 'const [value, setValue] = useState("组件 API、示例和代码应保持一致。");\n<Textarea value={value} maxLength={60} showCount onChange={event => setValue(event.target.value)} />', render: () => <ControlledTextareaDemo /> }, { title: "尺寸与状态", code: '<Space direction="vertical"><Textarea size="small" placeholder="Small" /><Textarea size="large" placeholder="Large" /><Textarea status="warning" defaultValue="需要确认" /><Textarea status="error" defaultValue="格式错误" /><Textarea readOnly value="只读内容" /><Textarea disabled value="禁用内容" /></Space>', render: () => <Space direction="vertical"><Textarea size="small" placeholder="Small" /><Textarea size="large" placeholder="Large" /><Textarea status="warning" defaultValue="需要确认" /><Textarea status="error" defaultValue="格式错误" /><Textarea readOnly value="只读内容" /><Textarea disabled value="禁用内容" /></Space> }], api: api.textarea },
  select: { title: "Select 选择器", description: "原生选择器、键盘操作、表单序列化和移动端体验。", code: '<Select defaultValue="a"><option value="a">选项一</option><option value="b">选项二</option></Select>', render: () => <Select defaultValue="a"><option value="a">选项一</option><option value="b">选项二</option></Select>, demos: [{ title: "尺寸与状态", code: '<Space direction="vertical"><Select size="small" placeholder="请选择"><option value="a">Small</option></Select><Select size="middle" status="warning" defaultValue="a"><option value="a">Warning</option></Select><Select size="large" status="error" defaultValue="a"><option value="a">Error</option></Select><Select loading><option>加载中</option></Select><Select disabled><option>禁用</option></Select></Space>', render: () => <Space direction="vertical"><Select size="small" placeholder="请选择"><option value="a">Small</option></Select><Select size="middle" status="warning" defaultValue="a"><option value="a">Warning</option></Select><Select size="large" status="error" defaultValue="a"><option value="a">Error</option></Select><Select loading><option>加载中</option></Select><Select disabled><option>禁用</option></Select></Space> }, { title: "受控模式", code: 'const [value, setValue] = useState("design");\n<Select value={value} onChange={event => setValue(event.target.value)}><option value="design">设计</option><option value="engineering">工程</option><option value="product">产品</option></Select>', render: () => <ControlledSelectDemo /> }], api: api.select },
  "input-number": { title: "InputNumber 数字输入", description: "边界、步长、精度、格式化和键盘操作。", code: '<InputNumber aria-label="数量" min={0} max={10} defaultValue={3} />', render: () => <InputNumber aria-label="数量" min={0} max={10} defaultValue={3} />, demos: [{ title: "受控与格式化", code: 'const [value, setValue] = useState<number | null>(1280);\n<InputNumber value={value} min={0} step={100} precision={2} onChange={setValue} />', render: () => <ControlledInputNumberDemo /> }], api: api["input-number"] },
  "date-picker": { title: "DatePicker 日期选择", description: "日期边界、尺寸、状态、受控值和清除。", code: '<DatePicker aria-label="发布日期" defaultValue="2026-09-06" />', render: () => <DatePicker aria-label="发布日期" defaultValue="2026-09-06" />, demos: [{ title: "受控与清除", code: 'const [value, setValue] = useState("2026-09-06");\n<DatePicker value={value} allowClear onChange={setValue} />', render: () => <ControlledDatePickerDemo /> }], api: api["date-picker"] },
  form: { title: "Form 表单", description: "字段关联、校验结果、提交值、布局和整体状态。", code: '<Form><Field label="站点名称" required><Input name="siteName" /></Field><Button type="submit">提交</Button></Form>', render: () => <Form><Field label="站点名称" required><Input name="siteName" /></Field><Button type="submit">提交</Button></Form>, demos: [{ title: "校验与提交", code: '<Form onFinish={(_data, values) => setMessage(values.siteName)} onFinishFailed={() => setMessage("请检查必填字段")}><Field label="站点名称" required><Input name="siteName" /></Field><Button type="submit">提交</Button></Form>', render: () => <FormValidationDemo /> }], api: api.form },
  upload: { title: "Upload 上传", description: "文件选择、拖放、受控列表和校验。", code: '<Upload accept="image/*" multiple maxCount={3}>选择图片</Upload>', render: () => <Upload accept="image/*" multiple maxCount={3}>选择图片</Upload>, demos: [{ title: "受控拖放区域", code: 'const [files, setFiles] = useState<File[]>([]);\n<Upload files={files} multiple maxCount={2} drag onFiles={setFiles}>拖放图片或点击选择</Upload>', render: () => <ControlledUploadDemo /> }], api: api.upload },
  "date-range-picker": { title: "DateRangePicker 日期范围", description: "受控开始和结束日期。", code: '<DateRangePicker start="2026-09-01" end="2026-09-06" onChange={() => undefined} />', render: () => <DateRangePicker start="2026-09-01" end="2026-09-06" onChange={() => undefined} /> },
  "time-picker": { title: "TimePicker 时间选择", description: "原生时间输入和键盘操作。", code: '<TimePicker aria-label="发布时间" />', render: () => <TimePicker aria-label="发布时间" /> },
  "color-picker": { title: "ColorPicker 颜色选择", description: "浏览器原生颜色选择。", code: '<ColorPicker defaultValue="#1677ff" />', render: () => <ColorPicker aria-label="品牌色" defaultValue="#1677ff" /> },
  checkbox: { title: "Checkbox 多选框", description: "独立选择和禁用状态。", code: '<Checkbox label="接受条款" defaultChecked />', render: () => <Checkbox label="接受条款" defaultChecked /> },
  radio: { title: "Radio 单选框", description: "使用相同 name 组成单选组。", code: '<Radio name="plan" label="基础版" defaultChecked />', render: () => <Radio name="plan" label="基础版" defaultChecked /> },
  switch: { title: "Switch 开关", description: "即时切换布尔状态。", code: '<Switch label="启用通知" defaultChecked />', render: () => <Switch label="启用通知" defaultChecked /> },
  slider: { title: "Slider 滑动输入", description: "范围、步长、禁用和键盘调整。", code: '<Slider aria-label="音量" min={0} max={100} defaultValue={40} />', render: () => <Slider aria-label="音量" min={0} max={100} defaultValue={40} /> },
  rate: { title: "Rate 评分", description: "受控或非受控星级评分。", code: '<Rate defaultValue={3} />', render: () => <Rate defaultValue={3} /> },
  autocomplete: { title: "AutoComplete 自动完成", description: "输入过滤和可访问列表框。", code: '<AutoComplete placeholder="输入城市" options={["Beijing", "Shanghai"]} />', render: () => <AutoComplete placeholder="输入城市" options={["Beijing", "Shanghai"]} /> },
  segmented: { title: "Segmented 分段控制", description: "在少量互斥选项之间切换。", code: '<Segmented options={["日", "周", "月"]} defaultValue="周" />', render: () => <Segmented options={["日", "周", "月"]} defaultValue="周" /> },
  cascader: { title: "Cascader 级联选择", description: "从层级数据中逐级选择。", code: '<Cascader options={[{ value: "zhejiang", label: "浙江" }]} />', render: () => <Cascader options={[{ value: "zhejiang", label: "浙江" }]} /> },
  "tree-select": { title: "TreeSelect 树选择", description: "从树形数据中选择节点。", code: '<TreeSelect treeData={[{ value: "docs", title: "文档" }]} />', render: () => <TreeSelect treeData={[{ value: "docs", title: "文档" }]} /> },
  transfer: { title: "Transfer 穿梭框", description: "在两个集合间移动条目。", code: '<Transfer dataSource={[{ key: "1", title: "成员一" }]} />', render: () => <Transfer dataSource={[{ key: "1", title: "成员一" }]} /> },
  mentions: { title: "Mentions 提及", description: "输入 @ 时显示匹配建议。", code: '<Mentions options={["alice", "bob"]} />', render: () => <Mentions options={["alice", "bob"]} /> },
  "input-otp": { title: "Input.OTP 验证码输入", description: "自动跳格和退格回退。", code: '<InputOTP length={6} />', render: () => <InputOTP length={6} /> },
};
