import { useState } from "react";
import { AutoComplete, Button, Cascader, Checkbox, ColorPicker, DatePicker, DateRangePicker, Field, Form, Input, InputNumber, InputOTP, Mentions, Radio, Rate, Segmented, Select, Slider, Space, Switch, Text, Textarea, TimePicker, Transfer, TreeSelect, Upload } from "../../../src/core";
import type { ComponentDocument } from "../../components/component-page";

function ControlledSelectDemo() {
  const [value, setValue] = useState("design");
  return <Space direction="vertical"><Select value={value} onChange={(event) => setValue(event.target.value)}><option value="design">设计</option><option value="engineering">工程</option><option value="product">产品</option></Select><Text tone="muted">当前值：{value}</Text></Space>;
}

function FormValidationDemo() {
  const [submitted, setSubmitted] = useState(false);
  return <Form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><Field label="站点名称" hint="显示在浏览器标题中" required><Input name="siteName" defaultValue="Gouno" /></Field><Field label="联系邮箱" error={submitted ? "请输入有效邮箱" : undefined} required><Input name="email" defaultValue="invalid" /></Field><Button type="submit" variant="primary">校验并提交</Button></Form>;
}
export const dataEntryDocuments: Record<string, ComponentDocument> = {
  "input-number": { title: "InputNumber 数字输入", description: "支持步长、边界、受控和非受控模式。", code: '<InputNumber min={0} max={10} defaultValue={3} />', render: () => <div className="max-w-xs"><InputNumber min={0} max={10} defaultValue={3} /></div> },
  "date-picker": { title: "DatePicker 日期选择", description: "原生日期选择和表单序列化。", code: '<DatePicker aria-label="发布日期" />', render: () => <DatePicker aria-label="发布日期" /> },
  "date-range-picker": { title:"DateRangePicker 日期范围", description:"受控开始和结束日期。", code:'<DateRangePicker start={start} end={end} onChange={setRange} />', render:()=> <DateRangePicker start="2026-09-01" end="2026-09-06" onChange={()=>undefined}/> },
  "time-picker": { title: "TimePicker 时间选择", description: "原生时间输入和键盘操作。", code: '<TimePicker aria-label="发布时间" />', render: () => <TimePicker aria-label="发布时间" /> },
  "color-picker": { title: "ColorPicker 颜色选择", description: "浏览器原生颜色选择。", code: '<ColorPicker defaultValue="#1677ff" />', render: () => <ColorPicker aria-label="品牌色" defaultValue="#1677ff" /> },
  upload: { title: "Upload 上传", description: "文件选择、列表、数量限制、移除和错误状态。", code: '<Upload accept="image/*" multiple onFiles={setFiles}>选择图片</Upload>', render: () => <Upload accept="image/*" multiple maxCount={3} onFiles={() => undefined}>选择图片</Upload>, demos: [{ title: "文件列表与移除", description: "非受控文件列表支持逐项移除。", code: '<Upload defaultFiles={[file]} onRemove={handleRemove} />', render: () => <Upload defaultFiles={[new File(["demo"], "cover.png", { type: "image/png" })]}>替换文件</Upload> }, { title: "禁用与错误", code: '<Upload disabled>禁止上传</Upload>\n<Upload error="文件过大" />', render: () => <Space direction="vertical"><Upload disabled>禁止上传</Upload><Upload error="文件超过 5 MB，请压缩后重试。">重新选择</Upload></Space> }], api: [{ name: "files", description: "受控文件列表", type: "File[]" }, { name: "defaultFiles", description: "非受控初始文件", type: "File[]" }, { name: "onFiles", description: "文件列表变化回调", type: "(files: File[]) => void" }, { name: "maxCount", description: "最大文件数", type: "number" }, { name: "maxSize", description: "单文件最大字节数", type: "number" }, { name: "error", description: "错误说明并设置无障碍关联", type: "ReactNode" }] },
  input: { title: "Input 输入框", description: "文本输入、前后图标、禁用和错误状态。", code: '<Input placeholder="请输入" />', render: () => <Space direction="vertical"><Input placeholder="默认输入框" /><Input disabled placeholder="禁用状态" /><Input aria-invalid="true" defaultValue="错误内容" /></Space> },
  textarea: { title: "Textarea 多行输入", description: "适用于较长文本输入。", code: '<Textarea rows={4} placeholder="请输入内容" />', render: () => <Textarea rows={4} placeholder="请输入内容" /> },
  select: { title: "Select 选择器", description: "保持原生表单序列化能力。", code: '<Select><option>选项一</option></Select>', render: () => <Select defaultValue="a"><option value="a">选项一</option><option value="b">选项二</option></Select>, demos: [{ title: "尺寸与状态", description: "紧凑、错误、只读语义和禁用状态。", code: '<Select size="compact" />\n<Select aria-invalid disabled />', render: () => <Space direction="vertical"><Select size="compact" defaultValue="a"><option value="a">紧凑选择器</option></Select><Select aria-invalid="true" defaultValue="error"><option value="error">错误状态</option></Select><Select disabled defaultValue="disabled"><option value="disabled">禁用状态</option></Select></Space> }, { title: "受控模式", code: 'const [value, setValue] = useState("design");\n<Select value={value} onChange={e => setValue(e.target.value)} />', render: () => <ControlledSelectDemo /> }] },
  checkbox: { title: "Checkbox 多选框", description: "独立选择和禁用状态。", code: '<Checkbox label="接受条款" />', render: () => <Space direction="vertical"><Checkbox label="接受条款" defaultChecked /><Checkbox label="禁用选项" disabled /></Space> },
  radio: { title: "Radio 单选框", description: "使用相同 name 组成单选组。", code: '<Radio name="plan" label="基础版" />', render: () => <Space><Radio name="plan" label="基础版" defaultChecked /><Radio name="plan" label="专业版" /></Space> },
  switch: { title: "Switch 开关", description: "即时切换布尔状态。", code: '<Switch label="启用通知" />', render: () => <Space direction="vertical"><Switch label="启用通知" defaultChecked /><Switch label="禁用" disabled /></Space> },
  slider: { title: "Slider 滑动输入", description: "范围、步长、禁用和键盘调整。", code: '<Slider min={0} max={100} defaultValue={40} />', render: () => <div className="max-w-md"><Slider aria-label="音量" min={0} max={100} defaultValue={40} /></div> },
  rate: { title: "Rate 评分", description: "受控或非受控星级评分。", code: '<Rate defaultValue={3} />', render: () => <Rate defaultValue={3} /> },
  autocomplete: { title: "AutoComplete 自动完成", description: "输入过滤和可访问列表框。", code: '<AutoComplete options={["Beijing", "Shanghai"]} />', render: () => <div className="max-w-sm"><AutoComplete placeholder="输入城市" options={["Beijing", "Shanghai", "Shenzhen", "Hangzhou"]} /></div> },
  segmented: { title: "Segmented 分段控制", description: "在少量互斥选项之间切换。", code: '<Segmented options={["日", "周", "月"]} />', render: () => <Segmented options={["日", "周", "月"]} defaultValue="周" /> },
  cascader: { title: "Cascader 级联选择", description: "从层级数据中逐级选择。", code: '<Cascader options={regions} onChange={setValue} />', render: () => <Cascader options={[{ value:"zhejiang", label:"浙江", children:[{ value:"hangzhou", label:"杭州" },{ value:"ningbo", label:"宁波" }]},{ value:"jiangsu", label:"江苏", children:[{ value:"nanjing", label:"南京" }]}]} /> },
  "tree-select": { title: "TreeSelect 树选择", description: "从树形数据中选择一个或多个节点。", code: '<TreeSelect treeData={nodes} />', render: () => <TreeSelect treeData={[{ value:"docs", title:"文档", children:[{ value:"api", title:"API" },{ value:"guide", title:"指南" }]}]} defaultValue="api" /> },
  transfer: { title: "Transfer 穿梭框", description: "在两个集合间移动和选择条目。", code: '<Transfer dataSource={items} defaultTargetKeys={["2"]} />', render: () => <Transfer dataSource={[{key:"1",title:"成员一"},{key:"2",title:"成员二"},{key:"3",title:"成员三"}]} defaultTargetKeys={["2"]} titles={["可选成员","已选择"]} /> },
  mentions: { title: "Mentions 提及", description: "输入 @ 时显示匹配建议。", code: '<Mentions options={["alice", "bob"]} />', render: () => <Mentions aria-label="评论" placeholder="输入 @ 提及成员" options={["alice","bob","charlie"]} /> },
  "input-otp": { title:"Input.OTP 验证码输入", description:"自动跳格、退格回退和一次性密码自动填充。", code:'<InputOTP length={6} onChange={setCode} />', render:()=> <InputOTP length={6} /> },
  form: { title:"Form 表单", description:"字段标签、帮助信息、错误关联和提交布局。", code:'<Form><Field label="名称"><Input /></Field></Form>', render:()=> <Form onSubmit={e=>e.preventDefault()}><Field label="站点名称" hint="显示在页面标题中" required><Input defaultValue="Gouno"/></Field><Field label="邮箱" error="请输入有效邮箱"><Input defaultValue="invalid"/></Field><Button type="submit" variant="primary">提交</Button></Form>, demos: [{ title: "提交校验", description: "提交后显示错误，并通过 aria-describedby 关联字段与错误信息。", code: '<Form onSubmit={validate}>\n  <Field label="联系邮箱" error={error} required>\n    <Input name="email" />\n  </Field>\n</Form>', render: () => <FormValidationDemo /> }, { title: "只读与禁用", code: '<Input readOnly value="只读内容" />\n<Input disabled value="禁用内容" />', render: () => <Space direction="vertical"><Field label="只读字段"><Input readOnly value="只读内容" /></Field><Field label="禁用字段"><Input disabled value="禁用内容" /></Field></Space> }] }
};
