import { Badge, Calendar, Carousel, Descriptions, Empty, Grid, Image, List, Skeleton, Space, Statistic, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Text, Timeline, Tree } from "../../../src/core";
import type { ComponentDocument } from "../../components/component-page";
export const dataDisplayDocuments: Record<string, ComponentDocument> = {
  list: { title: "List 列表", description: "基础分隔列表和自定义条目。", code: '<List data={items} renderItem={item => <Text>{item}</Text>} />', render: () => <List data={["Button", "Input", "Table"]} renderItem={item => <Text>{item}</Text>} /> },
  descriptions: { title: "Descriptions 描述列表", description: "展示对象属性和详情信息。", code: '<Descriptions columns={2} items={items} />', render: () => <Descriptions columns={2} bordered items={[{ label: "版本", children: "0.2.0" }, { label: "状态", children: <Badge tone="success">Stable</Badge> }]} /> },
  calendar: { title: "Calendar 日历", description: "日期网格、选中态和可选边界。", code: '<Calendar value={new Date()} onChange={setDate} />', render: () => <div className="max-w-md"><Calendar value={new Date(2026, 0, 15)} onChange={() => undefined} /></div> },
  image: { title: "Image 图片", description: "图片加载失败时提供可访问 fallback。", code: '<Image src="/cover.png" fallback={<Empty />} />', render: () => <Image src="/missing.png" alt="示例图片" fallback={<div className="rounded border p-10 text-center text-sm text-muted-foreground">Fallback</div>} /> },
  carousel: { title: "Carousel 轮播", description: "受控视觉轮播和键盘可达的操作按钮。", code: '<Carousel items={[<Card>One</Card>, <Card>Two</Card>]} />', render: () => <Carousel items={[<div key="1" className="p-12 text-center">Slide One</div>, <div key="2" className="p-12 text-center">Slide Two</div>]} /> },
  table: { title: "Table 表格", description: "统一表头、行、单元格和响应式容器样式。", code: '<Table><TableHeader>...</TableHeader><TableBody>...</TableBody></Table>', render: () => <Table><TableHeader><TableRow><TableHead>名称</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Gouno UI</TableCell><TableCell><Badge tone="success">正常</Badge></TableCell></TableRow></TableBody></Table>, demos: [{ title: "密度", description: "默认、紧凑和触控密度使用同一组表格结构。", code: '<Table density="compact">...</Table>\n<Table density="touch">...</Table>', render: () => <Space direction="vertical"><Table density="compact"><TableHeader><TableRow><TableHead>紧凑表格</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>构建任务</TableCell><TableCell>完成</TableCell></TableRow></TableBody></Table><Table density="touch"><TableHeader><TableRow><TableHead>触控表格</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>发布任务</TableCell><TableCell>等待</TableCell></TableRow></TableBody></Table></Space> }, { title: "加载与空状态", code: '<Skeleton className="h-24" />\n<Empty title="暂无数据" />', render: () => <Grid columns={2}><Skeleton className="h-32 w-full" /><Empty title="暂无数据" description="调整筛选条件后重试。" /></Grid> }] },
  statistic: { title: "Statistic 统计数值", description: "突出展示指标及单位。", code: '<Statistic title="访问量" value="12,480" />', render: () => <Grid columns={2}><Statistic title="访问量" value="12,480" /><Statistic title="增长" value="18.6" suffix="%" /></Grid> },
  timeline: { title: "Timeline 时间轴", description: "按顺序展示事件。", code: '<Timeline items={[{ title: "创建" }]} />', render: () => <Timeline items={[{ title:"创建项目", description:"09:00" },{ title:"完成构建", description:"09:12" }]} /> },
  tree: { title: "Tree 树", description: "层级展开、选择和复选。", code: '<Tree data={nodes} defaultExpandedKeys={["root"]} />', render: () => <Tree defaultExpandedKeys={["root"]} data={[{ key:"root", title:"组件", children:[{key:"core",title:"Core"},{key:"patterns",title:"Patterns"}]}]} /> }
};
