import { Button, Card, CardContent, CardHeader, Flex, Grid, Input, Layout, LayoutContent, LayoutFooter, LayoutHeader, LayoutSider, Separator, Space, Splitter, Text } from "../../../src/core";
import type { ComponentDocument } from "../../components/component-page";
export const layoutDocuments: Record<string, ComponentDocument> = {
  space: { title: "Space 间距", description: "统一水平或垂直元素间距。垂直布局默认沿父级宽度拉伸子项，想按内容宽度排列时显式使用 align=\"start\"。", code: '<Space size="lg"><Button>A</Button><Button>B</Button><Button>C</Button></Space>', render: () => <Space size="lg"><Button>A</Button><Button>B</Button><Button>C</Button></Space>, demos: [{ title: "垂直排列与宽度", code: '<div className="grid gap-6 md:grid-cols-2"><Space direction="vertical" align="start"><Button>按内容宽度</Button><Button>显式 align=start</Button></Space><Space direction="vertical"><Button>默认铺满父级</Button><Input placeholder="输入框与其他控件对齐" /></Space></div>', render: () => <div className="grid gap-6 md:grid-cols-2"><Space direction="vertical" align="start"><Button>按内容宽度</Button><Button>显式 align=start</Button></Space><Space direction="vertical"><Button>默认铺满父级</Button><Input placeholder="输入框与其他控件对齐" /></Space></div> }], api: [{ name: "direction", description: "排列方向", type: '"horizontal" | "vertical"', defaultValue: '"horizontal"' }, { name: "size", description: "元素间距或像素值", type: '"xs" | "sm" | "md" | "lg" | "xl" | number', defaultValue: '"md"' }, { name: "align", description: "交叉轴对齐；未设置时遵循 flex 默认行为，垂直排列为 stretch", type: '"start" | "end" | "center" | "baseline" | "stretch"' }, { name: "block", description: "让 Space 容器占满父级宽度", type: "boolean", defaultValue: "false" }, { name: "split", description: "在相邻子项之间插入分隔内容", type: "ReactNode" }, { name: "wrap", description: "是否允许换行", type: "boolean", defaultValue: "false" }] },
  flex: { title: "Flex 弹性布局", description: "对齐、分布、换行和方向。", code: '<Flex justify="between" align="center"><Text>左侧</Text><Button>右侧操作</Button></Flex>', render: () => <Flex justify="between" align="center"><Text>左侧</Text><Button>右侧操作</Button></Flex> },
  grid: { title: "Grid 网格", description: "固定列或自动适配的响应式网格。", code: '<Grid columns={3}>{[1, 2, 3].map((item) => <Card key={item} padding="sm">Card {item}</Card>)}</Grid>', render: () => <Grid columns={3}>{[1,2,3].map(i => <Card key={i} padding="sm">Card {i}</Card>)}</Grid> },
  separator: { title: "Separator 分隔线", description: "在内容区域之间建立视觉层级。", code: '<Separator />', render: () => <Space direction="vertical"><Text>第一部分</Text><Separator /><Text>第二部分</Text></Space> },
  card: { title: "Card 卡片", description: "内容分组、操作和交互表面。", code: '<Card><CardHeader title="标题" /><CardContent>内容</CardContent></Card>', render: () => <Card><CardHeader title="卡片标题" description="补充说明" /><CardContent>卡片正文内容</CardContent></Card> },
  splitter: { title:"Splitter 分隔面板", description:"通过拖动分隔条调整两个面板尺寸。", code:'<Splitter first={<PanelA />} second={<PanelB />} />', render:()=> <Splitter first={<div className="p-4">左侧面板</div>} second={<div className="p-4">右侧面板</div>} /> },
  "page-layout": { title:"Layout 页面布局", description:"Header、Sider、Content、Footer 的基础页面骨架。", code:'<Layout><LayoutHeader /><LayoutContent /></Layout>', render:()=> <Layout className="min-h-64 border"><LayoutHeader>Header</LayoutHeader><div className="flex flex-1"><LayoutSider>Sider</LayoutSider><LayoutContent>Content</LayoutContent></div><LayoutFooter>Footer</LayoutFooter></Layout> }
};
