import { Breadcrumb, Button, Collapse, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, Menu, Pagination, Steps, Tab, TabList, TabPanel, Tabs } from "../../../src/core";
import type { ComponentDocument } from "../../components/component-page";
export const navigationDocuments: Record<string, ComponentDocument> = {
  breadcrumb: { title: "Breadcrumb 面包屑", description: "表达当前页面在信息架构中的位置。", code: '<Breadcrumb items={[{ label: "首页", href: "/" }, { label: "组件" }]} />', render: () => <Breadcrumb items={[{ label: "首页", href: "#" }, { label: "Core" }, { label: "Breadcrumb" }]} /> },
  pagination: { title: "Pagination 分页", description: "分页边界、受控页码和总数展示。", code: '<Pagination page={2} total={86} pageSize={10} onChange={setPage} />', render: () => <Pagination page={2} total={86} pageSize={10} onChange={() => undefined} /> },
  steps: { title: "Steps 步骤条", description: "展示流程进度和当前步骤。", code: '<Steps current={1} items={[{ title: "填写" }, { title: "确认" }]} />', render: () => <Steps current={1} items={[{ title: "填写信息", description: "基本资料" }, { title: "确认订单" }, { title: "完成" }]} /> },
  anchor: { title: "Anchor 锚点", description: "页面内章节导航。", code: '<Anchor items={[{ key: "api", title: "API" }]} />', render: () => <div className="text-sm text-muted-foreground">Anchor API 已提供，可用于文档右侧章节导航。</div> },
  tabs: { title: "Tabs 标签页", description: "支持受控切换和方向键导航。", code: '<Tabs defaultValue="a"><TabList>...</TabList></Tabs>', render: () => <Tabs defaultValue="a"><TabList><Tab value="a">账户</Tab><Tab value="b">安全</Tab></TabList><TabPanel value="a">账户设置</TabPanel><TabPanel value="b">安全设置</TabPanel></Tabs> },
  collapse: { title: "Collapse 折叠面板", description: "展开一个或多个内容区域。", code: '<Collapse items={items} />', render: () => <Collapse defaultActiveKeys={["1"]} items={[{ key:"1", label:"什么是 Core？", children:"产品无关的基础组件。" },{ key:"2", label:"是否支持键盘？", children:"交互组件均提供语义与焦点行为。" }]} /> },
  dropdown: { title: "Dropdown 下拉菜单", description: "由按钮触发的操作菜单。", code: '<DropdownMenu><DropdownMenuTrigger>菜单</DropdownMenuTrigger>...</DropdownMenu>', render: () => <DropdownMenu><DropdownMenuTrigger asChild><Button>更多操作</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>编辑</DropdownMenuItem><DropdownMenuItem>复制</DropdownMenuItem><DropdownMenuItem variant="destructive">删除</DropdownMenuItem></DropdownMenuContent></DropdownMenu> },
  menu: { title: "Menu 菜单", description: "垂直或水平的可访问操作导航。", code: '<Menu items={items} selectedKeys={["home"]} />', render: () => <Menu ariaLabel="示例菜单" selectedKeys={["home"]} items={[{key:"home",label:"首页"},{key:"components",label:"组件"},{key:"disabled",label:"禁用",disabled:true}]} /> }
};
