import { useState, type ReactNode } from "react";
import { Badge, Breadcrumb, Button, Calendar, Card, CardContent, CardHeader, CardTitle, Carousel, ColorPicker, DatePicker, Descriptions, Divider, Empty, Flex, FloatButton, Grid, Heading, Image, Input, InputNumber, Kbd, List, Pagination, Progress, Result, Space, Spin, Steps, Text, TimePicker, Typography, Upload } from "../../src/core";
import { PageHeader, Panel } from "../../src/gouno";

const examples: Record<string, { title: string; description: string; code: string; render: () => ReactNode }> = {
  button: { title: "Button 按钮", description: "触发操作的基础按钮，支持变体、尺寸、图标和加载状态。", code: '<Button variant="primary">保存</Button>\n<Button loading>提交中</Button>', render: () => <Space wrap><Button variant="primary">主要按钮</Button><Button variant="secondary">次要按钮</Button><Button variant="danger">危险按钮</Button><Button loading>加载中</Button><Button disabled>禁用</Button></Space> },
  typography: { title: "Typography 排版", description: "统一标题、正文、辅助文字和语义色。", code: '<Heading level={2}>页面标题</Heading>\n<Text tone="muted">辅助说明</Text>', render: () => <Space direction="vertical"><Heading level={1}>一级标题</Heading><Heading level={2}>二级标题</Heading><Text size="lg">正文内容</Text><Text tone="muted">辅助说明</Text><Text tone="danger">错误提示</Text></Space> },
  layout: { title: "Space / Flex / Grid 布局", description: "不依赖业务的间距、弹性和网格布局原语。", code: '<Grid columns={3}><Card />...</Grid>', render: () => <Space direction="vertical"><Flex justify="between" align="center"><span>Flex 内容</span><Button size="sm">操作</Button></Flex><Divider /><Grid columns={3}>{[1,2,3].map(i => <Card key={i} padding="sm">Grid {i}</Card>)}</Grid></Space> },
  "input-number": { title: "InputNumber 数字输入", description: "支持步长、边界、受控和非受控模式。", code: '<InputNumber min={0} max={10} defaultValue={3} />', render: () => <div className="max-w-xs"><InputNumber min={0} max={10} defaultValue={3} /></div> },
  "date-time": { title: "Date / Time / Color 日期时间颜色", description: "使用浏览器原生控件保持表单序列化和移动端体验。", code: '<DatePicker />\n<TimePicker />\n<ColorPicker />', render: () => <Space wrap><DatePicker aria-label="日期" /><TimePicker aria-label="时间" /><ColorPicker aria-label="颜色" defaultValue="#1677ff" /></Space> },
  upload: { title: "Upload 上传", description: "文件选择、accept、multiple 和回调。", code: '<Upload accept="image/*" onFiles={files => ...}>选择文件</Upload>', render: () => <Upload accept="image/*" multiple onFiles={() => undefined}>选择图片</Upload> },
  breadcrumb: { title: "Breadcrumb 面包屑", description: "表达当前页面在信息架构中的位置。", code: '<Breadcrumb items={[{ label: "首页", href: "/" }, { label: "组件" }]} />', render: () => <Breadcrumb items={[{ label: "首页", href: "#" }, { label: "Core" }, { label: "Breadcrumb" }]} /> },
  pagination: { title: "Pagination 分页", description: "分页边界、受控页码和总数展示。", code: '<Pagination page={2} total={86} pageSize={10} onChange={setPage} />', render: () => <Pagination page={2} total={86} pageSize={10} onChange={() => undefined} /> },
  steps: { title: "Steps 步骤条", description: "展示流程进度和当前步骤。", code: '<Steps current={1} items={[{ title: "填写" }, { title: "确认" }]} />', render: () => <Steps current={1} items={[{ title: "填写信息", description: "基本资料" }, { title: "确认订单" }, { title: "完成" }]} /> },
  states: { title: "Empty / Result / Spin 状态", description: "空数据、结果和加载状态的统一表达。", code: '<Empty />\n<Result status="success" title="成功" />\n<Spin spinning />', render: () => <Grid columns={3}><Empty title="暂无数据" /><Result status="success" title="操作成功" /><Spin spinning tip="加载中"><div className="h-20 rounded border" /></Spin></Grid> },
  data: { title: "List / Descriptions 数据展示", description: "常用列表和键值描述布局。", code: '<List data={items} renderItem={item => <Text>{item}</Text>} />', render: () => <Grid columns={2}><List data={["Button", "Input", "Table"]} renderItem={item => <Text>{item}</Text>} /><Descriptions columns={2} items={[{ label: "版本", children: "0.2.0" }, { label: "状态", children: <Badge tone="success">Stable</Badge> }]} /></Grid> },
  calendar: { title: "Calendar 日历", description: "日期网格、选中态和可选边界。", code: '<Calendar value={new Date()} onChange={setDate} />', render: () => <div className="max-w-md"><Calendar value={new Date(2026, 0, 15)} onChange={() => undefined} /></div> },
  image: { title: "Image 图片", description: "图片加载失败时提供可访问 fallback。", code: '<Image src="/cover.png" fallback={<Empty />} />', render: () => <Image src="/missing.png" alt="示例图片" fallback={<div className="rounded border p-10 text-center text-sm text-muted-foreground">Fallback</div>} /> },
  carousel: { title: "Carousel 轮播", description: "受控视觉轮播和键盘可达的操作按钮。", code: '<Carousel items={[<Card>One</Card>, <Card>Two</Card>]} />', render: () => <Carousel items={[<div key="1" className="p-12 text-center">Slide One</div>, <div key="2" className="p-12 text-center">Slide Two</div>]} /> },
  misc: { title: "Anchor / FloatButton / Kbd", description: "页面锚点、悬浮操作和键盘快捷键提示。", code: '<FloatButton tooltip="返回顶部" />\n<Kbd>⌘ K</Kbd>', render: () => <Flex align="center" gap="lg"><Kbd>⌘ K</Kbd><FloatButton tooltip="返回顶部" className="static" /><Text tone="muted">悬浮按钮也可通过 href 使用链接模式。</Text></Flex> },
};
Object.assign(examples, {
  space: { ...examples.layout, title: "Space 间距", description: "统一水平或垂直元素间距。", code: '<Space size="lg"><Button>A</Button><Button>B</Button></Space>', render: () => <Space size="lg"><Button>A</Button><Button>B</Button><Button>C</Button></Space> },
  flex: { ...examples.layout, title: "Flex 弹性布局", description: "对齐、分布、换行和方向。", code: '<Flex justify="between" align="center">...</Flex>', render: () => <Flex justify="between" align="center"><Text>左侧</Text><Button>右侧操作</Button></Flex> },
  grid: { ...examples.layout, title: "Grid 网格", description: "固定列或自动适配的响应式网格。", code: '<Grid columns={3}>...</Grid>', render: () => <Grid columns={3}>{[1,2,3].map(i => <Card key={i} padding="sm">Card {i}</Card>)}</Grid> },
  "date-picker": { ...examples["date-time"], title: "DatePicker 日期选择", description: "原生日期选择和表单序列化。", code: '<DatePicker aria-label="发布日期" />', render: () => <DatePicker aria-label="发布日期" /> },
  "time-picker": { ...examples["date-time"], title: "TimePicker 时间选择", description: "原生时间输入和键盘操作。", code: '<TimePicker aria-label="发布时间" />', render: () => <TimePicker aria-label="发布时间" /> },
  "color-picker": { ...examples["date-time"], title: "ColorPicker 颜色选择", description: "浏览器原生颜色选择。", code: '<ColorPicker defaultValue="#1677ff" />', render: () => <ColorPicker aria-label="品牌色" defaultValue="#1677ff" /> },
  empty: { ...examples.states, title: "Empty 空状态", description: "无数据时的说明和操作入口。", code: '<Empty title="暂无数据" description="创建第一条记录" />', render: () => <Empty title="暂无数据" description="创建第一条记录后会显示在这里。" action={<Button variant="primary">新建</Button>} /> },
  result: { ...examples.states, title: "Result 结果", description: "操作结果和下一步入口。", code: '<Result status="success" title="操作成功" />', render: () => <Result status="success" title="操作成功" subTitle="数据已经保存" extra={<Button>返回列表</Button>} /> },
  spin: { ...examples.states, title: "Spin 加载", description: "局部内容加载遮罩。", code: '<Spin spinning tip="加载中"><Card /></Spin>', render: () => <Spin spinning tip="加载中"><div className="h-32 rounded border" /></Spin> },
  list: { ...examples.data, title: "List 列表", description: "基础分隔列表和自定义条目。", code: '<List data={items} renderItem={item => <Text>{item}</Text>} />', render: () => <List data={["Button", "Input", "Table"]} renderItem={item => <Text>{item}</Text>} /> },
  descriptions: { ...examples.data, title: "Descriptions 描述列表", description: "展示对象属性和详情信息。", code: '<Descriptions columns={2} items={items} />', render: () => <Descriptions columns={2} bordered items={[{ label: "版本", children: "0.2.0" }, { label: "状态", children: <Badge tone="success">Stable</Badge> }]} /> },
  anchor: { ...examples.misc, title: "Anchor 锚点", description: "页面内章节导航。", code: '<Anchor items={[{ key: "api", title: "API" }]} />', render: () => <div className="text-sm text-muted-foreground">Anchor API 已提供，可用于文档右侧章节导航。</div> },
  "float-button": { ...examples.misc, title: "FloatButton 悬浮按钮", description: "固定位置的快捷操作。", code: '<FloatButton tooltip="返回顶部" />', render: () => <FloatButton tooltip="返回顶部" className="static" /> },
  kbd: { ...examples.misc, title: "Kbd 键盘按键", description: "表达键盘快捷键。", code: '<Kbd>⌘</Kbd><Kbd>K</Kbd>', render: () => <Space><Kbd>⌘</Kbd><Kbd>K</Kbd></Space> },
});

export function CoreComponentPage({ component }: { component: string }) { const item = examples[component] || examples.button; const [tab, setTab] = useState<"preview"|"code">("preview"); return <div className="space-y-6"><PageHeader title={item.title} description={item.description} /><Panel><div className="mb-4 flex gap-1 border-b"><button className={`border-b-2 px-3 py-2 text-sm ${tab === "preview" ? "border-primary text-foreground" : "border-transparent text-muted-foreground"}`} onClick={() => setTab("preview")}>Preview</button><button className={`border-b-2 px-3 py-2 text-sm ${tab === "code" ? "border-primary text-foreground" : "border-transparent text-muted-foreground"}`} onClick={() => setTab("code")}>Code</button></div>{tab === "preview" ? <div className="min-h-40 rounded-md border bg-background p-6">{item.render()}</div> : <pre className="overflow-auto rounded-md bg-muted p-4 text-sm"><code>{item.code}</code></pre>}</Panel><Panel><Heading level={3}>状态与用法</Heading><Text tone="muted">所有 Core 组件使用 semantic tokens，支持键盘焦点、禁用态和表单关联。请优先使用受控模式承载业务状态。</Text></Panel></div>; }
