import { useState } from "react";
import { Badge, Breadcrumb, Button, Calendar, Card, CardContent, CardHeader, CardTitle, Container, DatePicker, Descriptions, Divider, Empty, Heading, Image, Input, InputNumber, Kbd, List, Pagination, Progress, Result, Spinner, Stack, Steps, Text, Timeline, Typography, Upload } from "../../src/core";
import { PageHeader, Panel, PanelHeader } from "../../src/gouno";

export function CoreOverview() {
  const [value, setValue] = useState(42);
  return <Container className="space-y-6">
    <PageHeader title="Gouno UI Core" description="纯产品无关基础组件：视觉、交互、可访问性和通用状态。" />
    <div className="grid gap-6 md:grid-cols-2">
      <Panel><PanelHeader title="Actions & feedback" description="组件可以独立使用，不依赖 Blog 或 Admin 业务。" /><Stack gap={3}><div className="flex flex-wrap items-center gap-2"><Button variant="primary">Primary</Button><Button variant="secondary">Secondary</Button><Button loading>Loading</Button><Badge tone="info">Info</Badge><Spinner /></div><Progress value={value} /><div className="flex items-center gap-2"><Input aria-label="进度" type="range" min="0" max="100" value={value} onChange={e => setValue(Number(e.target.value))} /><span className="text-sm tabular-nums">{value}%</span></div></Stack></Panel>
      <Panel><PanelHeader title="Typography & shortcuts" /><Stack gap={3}><Typography as="h2" className="text-2xl font-semibold">可组合的文字层级</Typography><Typography className="text-muted-foreground">基础组件只负责呈现和交互，不包含产品业务状态。</Typography><div className="flex items-center gap-2 text-sm">打开命令面板 <Kbd>⌘</Kbd><Kbd>K</Kbd></div></Stack></Panel>
      <Card><CardHeader><CardTitle>Statistic</CardTitle></CardHeader><CardContent><div className="grid grid-cols-2 gap-4"><Statistic title="Components" value="42" /><Statistic title="Coverage" value="86" suffix="%" /></div></CardContent></Card>
      <Panel><PanelHeader title="Timeline" /><Timeline items={[{ title: "Core API", description: "基础组件边界已建立" }, { title: "Patterns API", description: "复合交互持续补齐" }, { title: "Product API", description: "等待场景迁移" }]} /></Panel><Panel><PanelHeader title="Ant Design 基础能力" description="日期、数字、步骤、分页和上传均为独立 Core 组件。" /><Stack gap={3}><Heading level={3}>输入与导航</Heading><div className="flex flex-wrap items-center gap-2"><InputNumber defaultValue={3} min={0} aria-label="数量" /><DatePicker aria-label="日期" /><Upload accept="image/*">上传文件</Upload><Pagination page={2} total={42} /></div><Steps current={1} items={[{ title: "填写", description: "基本信息" }, { title: "确认" }, { title: "完成" }]} /></Stack></Panel><Panel><PanelHeader title="Data display & states" /><Stack gap={3}><Descriptions columns={2} items={[{ label: "版本", children: "0.2.0" }, { label: "状态", children: <Badge tone="success">Stable</Badge> }]} /><List data={["Button", "Input", "Table"]} renderItem={(item) => <Text>{item}</Text>} /><Empty title="空数据状态" description="可由调用方提供操作按钮。" /><Result status="success" title="组件验证通过" subTitle="Core 组件不依赖业务状态" /></Stack></Panel><Panel><PanelHeader title="Calendar & media" /><div className="grid gap-4 md:grid-cols-2"><Calendar value={new Date(2026, 0, 15)} /><Image src="/missing-image.png" alt="示例图片" fallback={<div className="rounded border p-8 text-center text-sm text-muted-foreground">Image fallback</div>} /></div></Panel>
    </div>
  </Container>;
}
