import { useState, type ReactNode } from "react";
import { LoaderCircle } from "lucide-react";
import { Affix, Alert, Layout, LayoutContent, LayoutFooter, LayoutHeader, LayoutSider, AutoComplete, BackTop, Avatar, AvatarFallback, Badge, Breadcrumb, Button, Calendar, Cascader, Card, CardContent, CardHeader, CardTitle, Carousel, Checkbox, Collapse, ColorPicker, DatePicker, DateRangePicker, Descriptions, Divider, Drawer, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger, Empty, Flex, FloatButton, Grid, Heading, Icon, Image, Input, Mentions, Menu, MessageProvider, useMessage, InputNumber, Kbd, List, Modal, NotificationProvider, useNotification, Pagination, Popconfirm, QRCode, Popover, PopoverContent, PopoverTrigger, Progress, Radio, Rate, Result, Tree, TreeSelect, Transfer, Segmented, Select, Skeleton, Slider, Splitter, Space, Spin, Statistic, Steps, Switch, Separator, Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tab, TabList, TabPanel, Tabs, Text, Textarea, TimePicker, Timeline, Tour, Tooltip, TooltipContent, TooltipProvider, TooltipTrigger, Typography, Upload, Watermark } from "../../src/core";
import { ComponentPage, type ComponentDocument } from "../components/component-page";


function ModalDemo() { const [open, setOpen] = useState(false); return <><Button onClick={() => setOpen(true)}>打开 Modal</Button><Modal open={open} title="编辑资料" onClose={() => setOpen(false)} footer={<Button onClick={() => setOpen(false)}>完成</Button>}><Text>Modal 内容和焦点回收示例。</Text></Modal></>; }
function DrawerDemo() { const [open, setOpen] = useState(false); return <><Button onClick={() => setOpen(true)}>打开 Drawer</Button><Drawer open={open} title="筛选条件" onClose={() => setOpen(false)}><Input placeholder="搜索" /></Drawer></>; }

function MessageDemo(){const api=useMessage();return <Space><Button onClick={()=>api.success("保存成功")}>Success</Button><Button onClick={()=>api.error("保存失败")}>Error</Button></Space>}
function NotificationDemo(){const api=useNotification();return <Button onClick={()=>api.open({title:"构建完成",description:"Showcase 已成功生成。"})}>打开通知</Button>}
function TourDemo(){const [open,setOpen]=useState(false);return <><Button onClick={()=>setOpen(true)}>开始引导</Button><Tour open={open} onClose={()=>setOpen(false)} steps={[{title:"欢迎",description:"这是第一步。"},{title:"组件目录",description:"从左侧选择组件。"}]}/></>}
const examples: Record<string, ComponentDocument> = {
  button: { title: "Button 按钮", description: "触发操作的基础按钮，支持变体、尺寸、图标和加载状态。", code: '<Button variant="primary">保存</Button>\n<Button loading>提交中</Button>', render: () => <Space wrap><Button variant="primary">主要按钮</Button><Button variant="secondary">次要按钮</Button><Button variant="danger">危险按钮</Button><Button loading>加载中</Button><Button disabled>禁用</Button></Space> },
  typography: { title: "Typography 排版", description: "统一标题、正文、辅助文字和语义色。", code: '<Heading level={2}>页面标题</Heading>\n<Text tone="muted">辅助说明</Text>', render: () => <Space direction="vertical"><Heading level={1}>一级标题</Heading><Heading level={2}>二级标题</Heading><Text size="lg">正文内容</Text><Text tone="muted">辅助说明</Text><Text tone="danger">错误提示</Text></Space> },
  layout: { title: "Space / Flex / Grid 布局", description: "不依赖业务的间距、弹性和网格布局原语。", code: '<Grid columns={3}><Card />...</Grid>', render: () => <Space direction="vertical"><Flex justify="between" align="center"><span>Flex 内容</span><Button size="sm">操作</Button></Flex><Divider /><Grid columns={3}>{[1,2,3].map(i => <Card key={i} padding="sm">Grid {i}</Card>)}</Grid></Space> },
  "input-number": { title: "InputNumber 数字输入", description: "支持步长、边界、受控和非受控模式。", code: '<InputNumber min={0} max={10} defaultValue={3} />', render: () => <div className="max-w-xs"><InputNumber min={0} max={10} defaultValue={3} /></div> },
  "date-time": { title: "Date / Time / Color 日期时间颜色", description: "使用浏览器原生控件保持表单序列化和移动端体验。", code: '<DatePicker />\n<TimePicker />\n<ColorPicker />', render: () => <Space wrap><DatePicker aria-label="日期" /><TimePicker aria-label="时间" /><ColorPicker aria-label="颜色" defaultValue="#1677ff" /></Space> },
  upload: { title: "Upload 上传", description: "文件选择、accept、multiple 和回调。", code: '<Upload accept="image/*" onFiles={files => ...}>选择文件</Upload>', render: () => <Upload accept="image/*" multiple onFiles={() => undefined}>选择图片</Upload> },
  breadcrumb: { title: "Breadcrumb 面包屑", description: "表达当前页面在信息架构中的位置。", code: '<Breadcrumb items={[{ label: "首页", href: "/" }, { label: "组件" }]} />', render: () => <Breadcrumb items={[{ label: "首页", href: "#" }, { label: "Core" }, { label: "Breadcrumb" }]} /> },
  pagination: { title: "Pagination 分页", description: "分页边界、受控页码和总数展示。", code: '<Pagination page={2} total={86} pageSize={10} onChange={setPage} />', render: () => <Pagination page={2} total={86} pageSize={10} onChange={() => undefined} /> },
  steps: { title: "Steps 步骤条", description: "展示流程进度和当前步骤。", code: '<Steps current={1} items={[{ title: "填写" }, { title: "确认" }]} />', render: () => <Steps current={1} items={[{ title: "填写信息", description: "基本资料" }, { title: "确认订单" }, { title: "完成" }]} /> },
  states: { title: "Empty / Result / Spin 状态", description: "空数据、结果和加载状态的统一表达。", code: '<Empty />\n<Result status="success" title="成功" />\n<Spin spinning />', render: () => <Grid columns={3}><Empty title="暂无数据" /><Result status="success" title="操作成功" /><Spin spinning tip="加载中"><div className="h-20 rounded border" /></Spin></Grid> },
  data: { title: "List / Descriptions 数据展示", description: "常用列表和键值描述布局。", code: '<List data={items} renderItem={item => <Text>{item}</Text>} />', render: () => <Grid columns={2}><List data={["Button", "Input", "Table"]} renderItem={item => <Text>{item}</Text>} /><Descriptions columns={2} items={[{ label: "版本", children: "0.2.0" }, { label: "状态", children: <Badge tone="success">Stable</Badge> }]} /></Grid> },
  calendar: { title: "Calendar 日历", description: "日期网格、选中态和可选边界。", code: '<Calendar value={new Date()} onChange={setDate} />', render: () => <div className="max-w-md"><Calendar value={new Date(2026, 0, 15)} onChange={() => undefined} /></div> },
  image: { title: "Image 图片", description: "图片加载失败时提供可访问 fallback。", code: '<Image src="/cover.png" fallback={<Empty />} />', render: () => <Image src="/missing.png" alt="示例图片" fallback={<div className="rounded border p-10 text-center text-sm text-muted-foreground">Fallback</div>} /> },
  carousel: { title: "Carousel 轮播", description: "受控视觉轮播和键盘可达的操作按钮。", code: '<Carousel items={[<Card>One</Card>, <Card>Two</Card>]} />', render: () => <Carousel items={[<div key="1" className="p-12 text-center">Slide One</div>, <div key="2" className="p-12 text-center">Slide Two</div>]} /> },
  misc: { title: "Anchor / FloatButton / Kbd", description: "页面锚点、悬浮操作和键盘快捷键提示。", code: '<FloatButton tooltip="返回顶部" />\n<Kbd>⌘ K</Kbd>', render: () => <Flex align="center" gap="lg"><Kbd>⌘ K</Kbd><FloatButton tooltip="返回顶部" className="static" /><Text tone="muted">悬浮按钮也可通过 href 使用链接模式。</Text></Flex> },
};
Object.assign(examples, {
  space: { ...examples.layout, title: "Space 间距", description: "统一水平或垂直元素间距。", code: '<Space size="lg"><Button>A</Button><Button>B</Button></Space>', render: () => <Space size="lg"><Button>A</Button><Button>B</Button><Button>C</Button></Space> },
  flex: { ...examples.layout, title: "Flex 弹性布局", description: "对齐、分布、换行和方向。", code: '<Flex justify="between" align="center">...</Flex>', render: () => <Flex justify="between" align="center"><Text>左侧</Text><Button>右侧操作</Button></Flex> },
  grid: { ...examples.layout, title: "Grid 网格", description: "固定列或自动适配的响应式网格。", code: '<Grid columns={3}>...</Grid>', render: () => <Grid columns={3}>{[1,2,3].map(i => <Card key={i} padding="sm">Card {i}</Card>)}</Grid> },
  "date-picker": { ...examples["date-time"], title: "DatePicker 日期选择", description: "原生日期选择和表单序列化。", code: '<DatePicker aria-label="发布日期" />', render: () => <DatePicker aria-label="发布日期" /> },
  "time-picker": { ...examples["date-time"], title: "TimePicker 时间选择", description: "原生时间输入和键盘操作。", code: '<TimePicker aria-label="发布时间" />', render: () => <TimePicker aria-label="发布时间" /> },
  "color-picker": { ...examples["date-time"], title: "ColorPicker 颜色选择", description: "浏览器原生颜色选择。", code: '<ColorPicker defaultValue="#1677ff" />', render: () => <ColorPicker aria-label="品牌色" defaultValue="#1677ff" /> },
  empty: { ...examples.states, title: "Empty 空状态", description: "无数据时的说明和操作入口。", code: '<Empty title="暂无数据" description="创建第一条记录" />', render: () => <Empty title="暂无数据" description="创建第一条记录后会显示在这里。" action={<Button variant="primary">新建</Button>} /> },
  result: { ...examples.states, title: "Result 结果", description: "操作结果和下一步入口。", code: '<Result status="success" title="操作成功" />', render: () => <Result status="success" title="操作成功" subTitle="数据已经保存" extra={<Button>返回列表</Button>} /> },
  spin: { ...examples.states, title: "Spin 加载", description: "局部内容加载遮罩。", code: '<Spin spinning tip="加载中"><Card /></Spin>', render: () => <Spin spinning tip="加载中"><div className="h-32 rounded border" /></Spin> },
  list: { ...examples.data, title: "List 列表", description: "基础分隔列表和自定义条目。", code: '<List data={items} renderItem={item => <Text>{item}</Text>} />', render: () => <List data={["Button", "Input", "Table"]} renderItem={item => <Text>{item}</Text>} /> },
  descriptions: { ...examples.data, title: "Descriptions 描述列表", description: "展示对象属性和详情信息。", code: '<Descriptions columns={2} items={items} />', render: () => <Descriptions columns={2} bordered items={[{ label: "版本", children: "0.2.0" }, { label: "状态", children: <Badge tone="success">Stable</Badge> }]} /> },
  anchor: { ...examples.misc, title: "Anchor 锚点", description: "页面内章节导航。", code: '<Anchor items={[{ key: "api", title: "API" }]} />', render: () => <div className="text-sm text-muted-foreground">Anchor API 已提供，可用于文档右侧章节导航。</div> },
  "float-button": { ...examples.misc, title: "FloatButton 悬浮按钮", description: "固定位置的快捷操作。", code: '<FloatButton tooltip="返回顶部" />', render: () => <FloatButton tooltip="返回顶部" className="static" /> },
  kbd: { ...examples.misc, title: "Kbd 键盘按键", description: "表达键盘快捷键。", code: '<Kbd>⌘</Kbd><Kbd>K</Kbd>', render: () => <Space><Kbd>⌘</Kbd><Kbd>K</Kbd></Space> },
});

Object.assign(examples, {
  input: { title: "Input 输入框", description: "文本输入、前后图标、禁用和错误状态。", code: '<Input placeholder="请输入" />', render: () => <Space direction="vertical"><Input placeholder="默认输入框" /><Input disabled placeholder="禁用状态" /><Input aria-invalid="true" defaultValue="错误内容" /></Space> },
  textarea: { title: "Textarea 多行输入", description: "适用于较长文本输入。", code: '<Textarea rows={4} placeholder="请输入内容" />', render: () => <Textarea rows={4} placeholder="请输入内容" /> },
  select: { title: "Select 选择器", description: "保持原生表单序列化能力。", code: '<Select><option>选项一</option></Select>', render: () => <Select defaultValue="a"><option value="a">选项一</option><option value="b">选项二</option></Select> },
  checkbox: { title: "Checkbox 多选框", description: "独立选择和禁用状态。", code: '<Checkbox label="接受条款" />', render: () => <Space direction="vertical"><Checkbox label="接受条款" defaultChecked /><Checkbox label="禁用选项" disabled /></Space> },
  radio: { title: "Radio 单选框", description: "使用相同 name 组成单选组。", code: '<Radio name="plan" label="基础版" />', render: () => <Space><Radio name="plan" label="基础版" defaultChecked /><Radio name="plan" label="专业版" /></Space> },
  switch: { title: "Switch 开关", description: "即时切换布尔状态。", code: '<Switch label="启用通知" />', render: () => <Space direction="vertical"><Switch label="启用通知" defaultChecked /><Switch label="禁用" disabled /></Space> },
  slider: { title: "Slider 滑动输入", description: "范围、步长、禁用和键盘调整。", code: '<Slider min={0} max={100} defaultValue={40} />', render: () => <div className="max-w-md"><Slider aria-label="音量" min={0} max={100} defaultValue={40} /></div> },
  rate: { title: "Rate 评分", description: "受控或非受控星级评分。", code: '<Rate defaultValue={3} />', render: () => <Rate defaultValue={3} /> },
  autocomplete: { title: "AutoComplete 自动完成", description: "输入过滤和可访问列表框。", code: '<AutoComplete options={["Beijing", "Shanghai"]} />', render: () => <div className="max-w-sm"><AutoComplete placeholder="输入城市" options={["Beijing", "Shanghai", "Shenzhen", "Hangzhou"]} /></div> },
  segmented: { title: "Segmented 分段控制", description: "在少量互斥选项之间切换。", code: '<Segmented options={["日", "周", "月"]} />', render: () => <Segmented options={["日", "周", "月"]} defaultValue="周" /> },
  collapse: { title: "Collapse 折叠面板", description: "展开一个或多个内容区域。", code: '<Collapse items={items} />', render: () => <Collapse defaultActiveKeys={["1"]} items={[{ key:"1", label:"什么是 Core？", children:"产品无关的基础组件。" },{ key:"2", label:"是否支持键盘？", children:"交互组件均提供语义与焦点行为。" }]} /> },
  badge: { title: "Badge / Tag 标签", description: "状态和分类的紧凑视觉标记。", code: '<Badge tone="success">已发布</Badge>', render: () => <Space wrap><Badge>默认</Badge><Badge tone="brand">品牌</Badge><Badge tone="success">成功</Badge><Badge tone="warning">警告</Badge><Badge tone="danger">危险</Badge></Space> },
  avatar: { title: "Avatar 头像", description: "图片头像和文字回退。", code: '<Avatar><AvatarFallback>GU</AvatarFallback></Avatar>', render: () => <Avatar><AvatarFallback>GU</AvatarFallback></Avatar> },
  card: { title: "Card 卡片", description: "内容分组、操作和交互表面。", code: '<Card><CardHeader title="标题" /><CardContent>内容</CardContent></Card>', render: () => <Card><CardHeader title="卡片标题" description="补充说明" /><CardContent>卡片正文内容</CardContent></Card> },
  tabs: { title: "Tabs 标签页", description: "支持受控切换和方向键导航。", code: '<Tabs defaultValue="a"><TabList>...</TabList></Tabs>', render: () => <Tabs defaultValue="a"><TabList><Tab value="a">账户</Tab><Tab value="b">安全</Tab></TabList><TabPanel value="a">账户设置</TabPanel><TabPanel value="b">安全设置</TabPanel></Tabs> },
  alert: { title: "Alert 警告提示", description: "页面内持续可见的重要信息。", code: '<Alert>这是一条提示</Alert>', render: () => <Alert>这是一条需要关注的信息。</Alert> },
  progress: { title: "Progress 进度条", description: "展示任务完成进度。", code: '<Progress value={60} />', render: () => <Space direction="vertical"><Progress value={60} /><Progress value={100} /></Space> },
  skeleton: { title: "Skeleton 骨架屏", description: "内容加载前的结构占位。", code: '<Skeleton className="h-8 w-full" />', render: () => <Space direction="vertical"><Skeleton className="h-8 w-48" /><Skeleton className="h-24 w-full" /></Space> },
  statistic: { title: "Statistic 统计数值", description: "突出展示指标及单位。", code: '<Statistic title="访问量" value="12,480" />', render: () => <Grid columns={2}><Statistic title="访问量" value="12,480" /><Statistic title="增长" value="18.6" suffix="%" /></Grid> },
  timeline: { title: "Timeline 时间轴", description: "按顺序展示事件。", code: '<Timeline items={[{ title: "创建" }]} />', render: () => <Timeline items={[{ title:"创建项目", description:"09:00" },{ title:"完成构建", description:"09:12" }]} /> },
  modal: { title: "Modal 对话框", description: "焦点锁定、Escape 关闭和焦点回收。", code: '<Modal open={open} title="标题" onClose={close}>内容</Modal>', render: () => <ModalDemo /> },
  drawer: { title: "Drawer 抽屉", description: "从侧边承载辅助任务。", code: '<Drawer open={open} title="筛选" onClose={close}>...</Drawer>', render: () => <DrawerDemo /> },
  popover: { title: "Popover 气泡卡片", description: "由触发器打开的轻量内容面板。", code: '<Popover><PopoverTrigger>打开</PopoverTrigger><PopoverContent>内容</PopoverContent></Popover>', render: () => <Popover><PopoverTrigger asChild><Button>打开 Popover</Button></PopoverTrigger><PopoverContent>可放置说明和操作。</PopoverContent></Popover> },
  tooltip: { title: "Tooltip 文字提示", description: "悬停或聚焦时解释控件。", code: '<Tooltip><TooltipTrigger>...</TooltipTrigger><TooltipContent>说明</TooltipContent></Tooltip>', render: () => <TooltipProvider><Tooltip><TooltipTrigger asChild><Button>聚焦或悬停</Button></TooltipTrigger><TooltipContent>补充说明</TooltipContent></Tooltip></TooltipProvider> },
  dropdown: { title: "Dropdown 下拉菜单", description: "由按钮触发的操作菜单。", code: '<DropdownMenu><DropdownMenuTrigger>菜单</DropdownMenuTrigger>...</DropdownMenu>', render: () => <DropdownMenu><DropdownMenuTrigger asChild><Button>更多操作</Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>编辑</DropdownMenuItem><DropdownMenuItem>复制</DropdownMenuItem><DropdownMenuItem variant="destructive">删除</DropdownMenuItem></DropdownMenuContent></DropdownMenu> },
});

Object.assign(examples, {
  separator: { title: "Separator 分隔线", description: "在内容区域之间建立视觉层级。", code: '<Separator />', render: () => <Space direction="vertical"><Text>第一部分</Text><Separator /><Text>第二部分</Text></Space> },
  table: { title: "Table 表格", description: "统一表头、行、单元格和响应式容器样式。", code: '<Table><TableHeader>...</TableHeader><TableBody>...</TableBody></Table>', render: () => <Table><TableHeader><TableRow><TableHead>名称</TableHead><TableHead>状态</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Gouno UI</TableCell><TableCell><Badge tone="success">正常</Badge></TableCell></TableRow></TableBody></Table> },
});

Object.assign(examples, {
  cascader: { title: "Cascader 级联选择", description: "从层级数据中逐级选择。", code: '<Cascader options={regions} onChange={setValue} />', render: () => <Cascader options={[{ value:"zhejiang", label:"浙江", children:[{ value:"hangzhou", label:"杭州" },{ value:"ningbo", label:"宁波" }]},{ value:"jiangsu", label:"江苏", children:[{ value:"nanjing", label:"南京" }]}]} /> },
  "tree-select": { title: "TreeSelect 树选择", description: "从树形数据中选择一个或多个节点。", code: '<TreeSelect treeData={nodes} />', render: () => <TreeSelect treeData={[{ value:"docs", title:"文档", children:[{ value:"api", title:"API" },{ value:"guide", title:"指南" }]}]} defaultValue="api" /> },
  transfer: { title: "Transfer 穿梭框", description: "在两个集合间移动和选择条目。", code: '<Transfer dataSource={items} defaultTargetKeys={["2"]} />', render: () => <Transfer dataSource={[{key:"1",title:"成员一"},{key:"2",title:"成员二"},{key:"3",title:"成员三"}]} defaultTargetKeys={["2"]} titles={["可选成员","已选择"]} /> },
  mentions: { title: "Mentions 提及", description: "输入 @ 时显示匹配建议。", code: '<Mentions options={["alice", "bob"]} />', render: () => <Mentions aria-label="评论" placeholder="输入 @ 提及成员" options={["alice","bob","charlie"]} /> },
  tree: { title: "Tree 树", description: "层级展开、选择和复选。", code: '<Tree data={nodes} defaultExpandedKeys={["root"]} />', render: () => <Tree defaultExpandedKeys={["root"]} data={[{ key:"root", title:"组件", children:[{key:"core",title:"Core"},{key:"patterns",title:"Patterns"}]}]} /> },
  menu: { title: "Menu 菜单", description: "垂直或水平的可访问操作导航。", code: '<Menu items={items} selectedKeys={["home"]} />', render: () => <Menu ariaLabel="示例菜单" selectedKeys={["home"]} items={[{key:"home",label:"首页"},{key:"components",label:"组件"},{key:"disabled",label:"禁用",disabled:true}]} /> },
  qrcode: { title: "QRCode 二维码", description: "生成可扫描二维码，支持尺寸、颜色和纠错级别。", code: '<QRCode value="https://gouno.com" />', render: () => <QRCode value="https://github.com/rushairer/gouno-ui" ariaLabel="Gouno UI repository QR code" /> },
  watermark: { title: "Watermark 水印", description: "为内容区域增加重复文字水印。", code: '<Watermark content="Gouno"><Card /></Watermark>', render: () => <Watermark content="Gouno UI"><div className="h-48 rounded-md border p-6">受保护的内容区域</div></Watermark> },
  affix: { title: "Affix 固钉", description: "通过 sticky 定位固定局部操作。", code: '<Affix offsetTop={16}><Button>固定操作</Button></Affix>', render: () => <Affix offsetTop={16}><Button>固定操作</Button></Affix> },
  "back-top": { title: "BackTop 回到顶部", description: "平滑滚动到页面顶部。", code: '<BackTop />', render: () => <BackTop className="static" /> },
});

Object.assign(examples, {
  splitter: { title:"Splitter 分隔面板", description:"通过拖动分隔条调整两个面板尺寸。", code:'<Splitter first={<PanelA />} second={<PanelB />} />', render:()=> <Splitter first={<div className="p-4">左侧面板</div>} second={<div className="p-4">右侧面板</div>} /> },
  "page-layout": { title:"Layout 页面布局", description:"Header、Sider、Content、Footer 的基础页面骨架。", code:'<Layout><LayoutHeader /><LayoutContent /></Layout>', render:()=> <Layout className="min-h-64 border"><LayoutHeader>Header</LayoutHeader><div className="flex flex-1"><LayoutSider>Sider</LayoutSider><LayoutContent>Content</LayoutContent></div><LayoutFooter>Footer</LayoutFooter></Layout> },
  "input-otp": { title:"Input.OTP 验证码输入", description:"自动跳格、退格回退和一次性密码自动填充。", code:'<InputOTP length={6} onChange={setCode} />', render:()=> <InputOTP length={6} /> },
  popconfirm: { title:"Popconfirm 气泡确认", description:"在危险或不可逆操作前请求确认。", code:'<Popconfirm title="确认删除？"><Button>删除</Button></Popconfirm>', render:()=> <Popconfirm title="确认删除？" description="删除后无法恢复。" danger><Button variant="danger">删除</Button></Popconfirm> },
  message: { title:"Message 全局提示", description:"短暂反馈操作结果。", code:'const message = useMessage(); message.success("保存成功")', render:()=> <MessageProvider><MessageDemo/></MessageProvider> },
  notification: { title:"Notification 通知提醒", description:"展示标题和补充描述的全局通知。", code:'notification.open({ title: "构建完成" })', render:()=> <NotificationProvider><NotificationDemo/></NotificationProvider> },
  tour: { title:"Tour 漫游式引导", description:"分步介绍页面能力。", code:'<Tour open={open} steps={steps} onClose={close} />', render:()=> <TourDemo/> },
});

Object.assign(examples, {
  icon: { title:"Icon 图标", description:"统一图标尺寸、旋转、加载动画和无障碍标签。", code:'<Icon icon={<LoaderCircle />} spin label="Loading" />', render:()=> <Space><Icon icon={<LoaderCircle/>}/><Icon icon={<LoaderCircle/>} spin label="Loading"/><Icon icon={<LoaderCircle/>} rotate={45}/></Space> },
  form: { title:"Form 表单", description:"字段标签、帮助信息、错误关联和提交布局。", code:'<Form><Field label="名称"><Input /></Field></Form>', render:()=> <Form onSubmit={e=>e.preventDefault()}><Field label="站点名称" hint="显示在页面标题中" required><Input defaultValue="Gouno"/></Field><Field label="邮箱" error="请输入有效邮箱"><Input defaultValue="invalid"/></Field><Button type="submit" variant="primary">提交</Button></Form> },
  "date-range-picker": { title:"DateRangePicker 日期范围", description:"受控开始和结束日期。", code:'<DateRangePicker start={start} end={end} onChange={setRange} />', render:()=> <DateRangePicker start="2026-09-01" end="2026-09-06" onChange={()=>undefined}/> },
});

export function CoreComponentPage({ component }: { component: string }) { return <ComponentPage document={examples[component] || examples.button} />; }
