import type { ReactNode } from "react";
import {
  AlignLeft,
  Anchor,
  ArrowLeftRight,
  ArrowUpToLine,
  AtSign,
  Bell,
  Calendar,
  CalendarDays,
  CalendarRange,
  ChartColumn,
  ChevronRight,
  ChevronsLeftRight,
  ChevronsUpDown,
  CircleCheck,
  CircleChevronDown,
  CircleDot,
  CircleHelp,
  CirclePlus,
  CircleUserRound,
  ClipboardList,
  Clock3,
  Columns2,
  Columns3,
  CreditCard,
  FileText,
  Frame,
  GalleryHorizontal,
  Gauge,
  Grid3X3,
  Hash,
  Heading1,
  History,
  Home,
  ImageIcon,
  Inbox,
  Keyboard,
  KeyRound,
  LayoutTemplate,
  List,
  ListChecks,
  ListFilter,
  ListTree,
  LoaderCircle,
  LogIn,
  Mail,
  Menu,
  MessageCircleQuestion,
  MessageSquare,
  MessageSquareMore,
  Minus,
  MousePointerClick,
  MoveHorizontal,
  Network,
  Palette,
  PanelRightOpen,
  PanelsTopLeft,
  Pin,
  Pipette,
  QrCode,
  RefreshCw,
  Route,
  Rows3,
  ScanLine,
  Search,
  ShieldCheck,
  Shapes,
  SlidersHorizontal,
  SquareCheckBig,
  SquareStack,
  Stamp,
  Star,
  StretchHorizontal,
  Table2,
  Tags,
  TextCursorInput,
  ToggleRight,
  TreePine,
  TriangleAlert,
  Type,
  Upload,
  UserCog,
} from "lucide-react";
import { componentProgress } from "./component-progress";

export type ShowcaseWorkspace = "gouno-ui" | "blog" | "blog-admin" | "gosso-admin";
export type ShowcaseLayer = "core" | "theme" | "patterns" | "gouno";
export type ShowcasePresentation = "app-shell" | "standalone";

export type ShowcasePage = {
  id: string;
  name: string;
  nameZh: string;
  label: string;
  progress: number;
  icon: ReactNode;
  presentation?: ShowcasePresentation;
};

export type ShowcaseGroup = {
  workspace: ShowcaseWorkspace;
  layer?: ShowcaseLayer;
  group: string;
  items: ShowcasePage[];
};

const item = (
  id: string,
  name: string,
  nameZh: string,
  progress: number,
  icon: ReactNode,
  presentation: ShowcasePresentation = "app-shell",
): ShowcasePage => ({
  id,
  name,
  nameZh,
  label: `${name} ${nameZh}`,
  progress: componentProgress(id, progress),
  icon,
  presentation,
});

export const showcaseCatalog: ShowcaseGroup[] = [
  { workspace: "gouno-ui", layer: "core", group: "General 通用", items: [
    item("core-button", "Button", "按钮", 100, <MousePointerClick />),
    item("core-icon", "Icon", "图标", 85, <Shapes />),
    item("core-typography", "Typography", "排版", 78, <Type />),
    item("core-kbd", "Kbd", "键盘按键", 90, <Keyboard />),
    item("core-badge", "Badge", "徽标数", 100, <CircleDot />),
    item("core-tag", "Tag", "标签", 100, <Tags />),
    item("core-avatar", "Avatar", "头像", 82, <CircleUserRound />),
  ]},
  { workspace: "gouno-ui", layer: "core", group: "Layout 布局", items: [
    item("core-space", "Space", "间距", 100, <MoveHorizontal />),
    item("core-flex", "Flex", "弹性布局", 78, <StretchHorizontal />),
    item("core-grid", "Grid", "网格", 72, <Grid3X3 />),
    item("core-separator", "Separator", "分隔线", 90, <Minus />),
    item("core-card", "Card", "卡片", 100, <CreditCard />),
    item("core-splitter", "Splitter", "分隔面板", 68, <Columns3 />),
    item("core-page-layout", "Layout", "页面布局", 75, <LayoutTemplate />),
  ]},
  { workspace: "gouno-ui", layer: "core", group: "Data Entry 数据录入", items: [
    item("core-input-number", "InputNumber", "数字输入框", 100, <Hash />),
    item("core-date-picker", "DatePicker", "日期选择器", 100, <CalendarDays />),
    item("core-date-range-picker", "DateRangePicker", "日期范围选择器", 68, <CalendarRange />),
    item("core-time-picker", "TimePicker", "时间选择器", 68, <Clock3 />),
    item("core-color-picker", "ColorPicker", "颜色选择器", 70, <Pipette />),
    item("core-upload", "Upload", "上传", 100, <Upload />),
    item("core-input", "Input", "输入框", 100, <TextCursorInput />),
    item("core-textarea", "Textarea", "多行输入框", 100, <AlignLeft />),
    item("core-select", "Select", "选择器", 100, <ListFilter />),
    item("core-checkbox", "Checkbox", "多选框", 78, <SquareCheckBig />),
    item("core-radio", "Radio", "单选框", 72, <CircleDot />),
    item("core-switch", "Switch", "开关", 78, <ToggleRight />),
    item("core-slider", "Slider", "滑动输入条", 72, <SlidersHorizontal />),
    item("core-rate", "Rate", "评分", 68, <Star />),
    item("core-autocomplete", "AutoComplete", "自动完成", 86, <Search />),
    item("core-segmented", "Segmented", "分段控制器", 70, <Columns2 />),
    item("core-cascader", "Cascader", "级联选择器", 65, <ListTree />),
    item("core-tree-select", "TreeSelect", "树选择器", 84, <TreePine />),
    item("core-transfer", "Transfer", "穿梭框", 68, <ArrowLeftRight />),
    item("core-mentions", "Mentions", "提及", 65, <AtSign />),
    item("core-input-otp", "Input.OTP", "验证码输入框", 75, <KeyRound />),
    item("core-form", "Form", "表单", 100, <ClipboardList />),
  ]},
  { workspace: "gouno-ui", layer: "core", group: "Navigation 导航", items: [
    item("core-breadcrumb", "Breadcrumb", "面包屑", 78, <ChevronRight />),
    item("core-pagination", "Pagination", "分页", 100, <ChevronsLeftRight />),
    item("core-steps", "Steps", "步骤条", 75, <ListChecks />),
    item("core-anchor", "Anchor", "锚点", 65, <Anchor />),
    item("core-tabs", "Tabs", "标签页", 100, <PanelsTopLeft />),
    item("core-collapse", "Collapse", "折叠面板", 72, <ChevronsUpDown />),
    item("core-dropdown", "Dropdown", "下拉菜单", 78, <CircleChevronDown />),
    item("core-menu", "Menu", "导航菜单", 68, <Menu />),
  ]},
  { workspace: "gouno-ui", layer: "core", group: "Data Display 数据展示", items: [
    item("core-list", "List", "列表", 70, <List />),
    item("core-descriptions", "Descriptions", "描述列表", 72, <Rows3 />),
    item("core-calendar", "Calendar", "日历", 68, <Calendar />),
    item("core-image", "Image", "图片", 72, <ImageIcon />),
    item("core-carousel", "Carousel", "走马灯", 68, <GalleryHorizontal />),
    item("core-table", "Table", "表格", 100, <Table2 />),
    item("core-statistic", "Statistic", "统计数值", 72, <ChartColumn />),
    item("core-timeline", "Timeline", "时间轴", 70, <History />),
    item("core-tree", "Tree", "树形控件", 78, <Network />),
  ]},
  { workspace: "gouno-ui", layer: "core", group: "Feedback 反馈", items: [
    item("core-empty", "Empty", "空状态", 82, <Inbox />),
    item("core-result", "Result", "结果页", 78, <CircleCheck />),
    item("core-spin", "Spin", "加载指示器", 72, <LoaderCircle />),
    item("core-alert", "Alert", "警告提示", 82, <TriangleAlert />),
    item("core-progress", "Progress", "进度条", 100, <Gauge />),
    item("core-skeleton", "Skeleton", "骨架屏", 75, <ScanLine />),
    item("core-modal", "Modal", "模态对话框", 100, <SquareStack />),
    item("core-drawer", "Drawer", "抽屉", 100, <PanelRightOpen />),
    item("core-popover", "Popover", "气泡卡片", 78, <MessageSquareMore />),
    item("core-tooltip", "Tooltip", "文字提示", 78, <MessageCircleQuestion />),
    item("core-popconfirm", "Popconfirm", "气泡确认框", 78, <CircleHelp />),
    item("core-message", "Message", "全局提示", 75, <MessageSquare />),
    item("core-notification", "Notification", "通知提醒框", 75, <Bell />),
    item("core-tour", "Tour", "漫游式引导", 68, <Route />),
  ]},
  { workspace: "gouno-ui", layer: "core", group: "Other 其他", items: [
    item("core-float-button", "FloatButton", "悬浮按钮", 65, <CirclePlus />),
    item("core-qrcode", "QRCode", "二维码", 72, <QrCode />),
    item("core-watermark", "Watermark", "水印", 70, <Stamp />),
    item("core-affix", "Affix", "固钉", 62, <Pin />),
    item("core-back-top", "BackTop", "回到顶部", 68, <ArrowUpToLine />),
  ]},
  { workspace: "gouno-ui", layer: "theme", group: "Theme System 主题系统", items: [
    item("theme-system", "Theme System", "主题系统", 90, <Palette />),
  ]},
  { workspace: "gouno-ui", layer: "patterns", group: "Admitted Patterns 已认证模式", items: [
    item("pattern-bulk-action-bar", "BulkActionBar", "批量操作栏", 100, <ListChecks />),
  ]},
  { workspace: "gouno-ui", layer: "gouno", group: "Application Structure 应用结构", items: [
    item("gouno-app-shell", "AppShell", "应用框架", 90, <PanelsTopLeft />),
    item("gouno-page-container", "PageContainer", "页面容器", 90, <Frame />),
    item("gouno-page-header", "PageHeader", "页面标题", 100, <Heading1 />),
  ]},
  { workspace: "blog", group: "Migrated Pages 已迁移页面", items: [] },
  { workspace: "blog-admin", group: "Content 内容管理", items: [
    item("blog-admin-posts", "Posts", "文章管理", 100, <FileText />),
    item("blog-admin-categories", "Categories", "分类管理", 100, <ListTree />),
    item("blog-admin-tags", "Tags", "标签管理", 100, <Tags />),
    item("blog-admin-pages", "Pages", "单页管理", 100, <FileText />),
    item("blog-admin-comments", "Comments", "评论审核", 100, <MessageSquare />),
  ]},
  { workspace: "blog-admin", group: "Site 站点管理", items: [
    item("blog-admin-users", "Members", "成员与权限", 100, <CircleUserRound />),
    item("blog-admin-site-settings", "Site Settings", "站点设置", 100, <SlidersHorizontal />),
  ]},
  { workspace: "gosso-admin", group: "Application Pages 应用页", items: [
    item("gosso-overview", "Overview", "概览", 100, <Home />),
    item("gosso-account-settings", "Account Settings", "账户设置", 100, <UserCog />),
    item("gosso-system-management", "System Management", "系统管理", 100, <ShieldCheck />),
    item("gosso-not-found", "Not Found", "未找到", 100, <CircleHelp />),
  ]},
  { workspace: "gosso-admin", group: "Authentication Pages 认证页", items: [
    item("gosso-login", "Login", "登录", 100, <LogIn />, "standalone"),
    item("gosso-forgot-password", "Forgot Password", "忘记密码", 100, <Mail />, "standalone"),
    item("gosso-reset-password", "Reset Password", "重置密码", 100, <KeyRound />, "standalone"),
    item("gosso-callback", "Auth Callback", "授权回调", 100, <RefreshCw />, "standalone"),
  ]},
];