export type CoreRuntimeFamilyReview = "covered" | "needs-review" | "unassigned";

export type CoreRuntimeFamilyCoverage = {
  familyId: `core-${string}` | null;
  review: CoreRuntimeFamilyReview;
  note?: string;
};

/**
 * Inventory of every PascalCase runtime value exported from @gouno/ui/core.
 *
 * A family is a visible Showcase page, not necessarily a 1:1 component page.
 * Tightly coupled public siblings may share one family (for example
 * ButtonLink/IconButtonLink/ChoiceButton -> Button). `unassigned` is deliberate:
 * it keeps a public export visible to the sealing audit until product evidence
 * justifies a family, an existing family explicitly absorbs it, or the export is
 * reconsidered.
 */
export const coreRuntimeFamilyCoverage = {
  Button: { familyId: "core-button", review: "covered" },
  ButtonLink: { familyId: "core-button", review: "covered" },
  IconButton: { familyId: "core-button", review: "covered" },
  IconButtonLink: { familyId: "core-button", review: "covered" },
  ChoiceButton: { familyId: "core-button", review: "covered" },
  NavigationProvider: { familyId: "core-button", review: "covered" },
  Icon: { familyId: "core-icon", review: "covered" },
  Badge: { familyId: "core-badge", review: "covered" },
  Tag: { familyId: "core-tag", review: "covered" },
  CheckableTag: { familyId: "core-tag", review: "covered" },
  Card: { familyId: "core-card", review: "covered" },
  CardHeader: { familyId: "core-card", review: "covered" },
  CardTitle: { familyId: "core-card", review: "covered" },
  CardDescription: { familyId: "core-card", review: "covered" },
  CardContent: { familyId: "core-card", review: "covered" },
  CardFooter: { familyId: "core-card", review: "covered" },
  Spinner: { familyId: "core-spin", review: "covered" },
  Progress: { familyId: "core-progress", review: "covered" },
  AspectRatio: {
    familyId: null,
    review: "unassigned",
    note: "No visible Showcase family or real-product fixture evidence yet.",
  },
  Kbd: { familyId: "core-kbd", review: "covered" },
  Heading: { familyId: "core-typography", review: "covered" },
  Text: { familyId: "core-typography", review: "covered" },
  Typography: { familyId: "core-typography", review: "covered" },
  Input: { familyId: "core-input", review: "covered" },
  SearchField: {
    familyId: "core-input",
    review: "needs-review",
    note: "Same source family as Input; family docs need an explicit SearchField contract check.",
  },
  Textarea: { familyId: "core-textarea", review: "covered" },
  Select: { familyId: "core-select", review: "covered" },
  Field: {
    familyId: "core-form",
    review: "needs-review",
    note: "Form anatomy export is public but not yet explicitly certified in the Form family docs.",
  },
  FormField: { familyId: "core-form", review: "needs-review" },
  FieldGroup: { familyId: "core-form", review: "needs-review" },
  FieldSet: { familyId: "core-form", review: "needs-review" },
  FieldLegend: { familyId: "core-form", review: "needs-review" },
  FieldLabel: { familyId: "core-form", review: "needs-review" },
  Checkbox: { familyId: "core-checkbox", review: "covered" },
  Radio: { familyId: "core-radio", review: "covered" },
  Switch: { familyId: "core-switch", review: "covered" },
  CheckboxField: {
    familyId: "core-checkbox",
    review: "needs-review",
    note: "Public convenience wrapper has no real-product fixture evidence yet.",
  },
  CheckboxGroup: { familyId: "core-checkbox", review: "needs-review" },
  FormLayout: { familyId: "core-form", review: "covered" },
  Form: { familyId: "core-form", review: "covered" },
  FormGrid: { familyId: "core-form", review: "needs-review" },
  FormActions: { familyId: "core-form", review: "needs-review" },
  OverlayForm: { familyId: "core-form", review: "needs-review" },
  Tabs: { familyId: "core-tabs", review: "covered" },
  TabList: { familyId: "core-tabs", review: "needs-review" },
  Tab: { familyId: "core-tabs", review: "needs-review" },
  TabPanel: { familyId: "core-tabs", review: "needs-review" },
  Modal: { familyId: "core-modal", review: "covered" },
  Drawer: { familyId: "core-drawer", review: "covered" },
  Alert: { familyId: "core-alert", review: "covered" },
  Skeleton: { familyId: "core-skeleton", review: "covered" },
  Statistic: { familyId: "core-statistic", review: "covered" },
  Timeline: { familyId: "core-timeline", review: "covered" },
  Container: {
    familyId: null,
    review: "unassigned",
    note: "Low-level layout primitive has no visible canonical family yet.",
  },
  Stack: {
    familyId: null,
    review: "unassigned",
    note: "Low-level layout primitive has no visible canonical family yet.",
  },
  Table: { familyId: "core-table", review: "covered" },
  TableHeader: { familyId: "core-table", review: "covered" },
  TableBody: { familyId: "core-table", review: "covered" },
  TableFooter: { familyId: "core-table", review: "covered" },
  TableHead: { familyId: "core-table", review: "covered" },
  TableRow: { familyId: "core-table", review: "covered" },
  TableCell: { familyId: "core-table", review: "covered" },
  TableCaption: { familyId: "core-table", review: "covered" },
  Separator: { familyId: "core-separator", review: "covered" },
  Avatar: { familyId: "core-avatar", review: "covered" },
  AvatarImage: { familyId: "core-avatar", review: "needs-review" },
  AvatarFallback: { familyId: "core-avatar", review: "needs-review" },
  Divider: {
    familyId: "core-separator",
    review: "needs-review",
    note: "Compatibility-style layout sibling needs explicit family documentation review.",
  },
  Space: { familyId: "core-space", review: "covered" },
  Flex: { familyId: "core-flex", review: "covered" },
  Grid: { familyId: "core-grid", review: "covered" },
  InputNumber: { familyId: "core-input-number", review: "covered" },
  DatePicker: { familyId: "core-date-picker", review: "covered" },
  DateRangePicker: { familyId: "core-date-range-picker", review: "covered" },
  TimePicker: { familyId: "core-time-picker", review: "covered" },
  ColorPicker: { familyId: "core-color-picker", review: "covered" },
  Upload: { familyId: "core-upload", review: "covered" },
  Breadcrumb: { familyId: "core-breadcrumb", review: "covered" },
  Pagination: { familyId: "core-pagination", review: "covered" },
  Steps: { familyId: "core-steps", review: "covered" },
  Empty: { familyId: "core-empty", review: "covered" },
  Result: { familyId: "core-result", review: "covered" },
  List: { familyId: "core-list", review: "covered" },
  Descriptions: { familyId: "core-descriptions", review: "covered" },
  Image: { familyId: "core-image", review: "covered" },
  Calendar: { familyId: "core-calendar", review: "covered" },
  App: {
    familyId: null,
    review: "unassigned",
    note: "Generic min-height wrapper is public but has no visible family or product evidence.",
  },
  FloatButton: { familyId: "core-float-button", review: "covered" },
  Anchor: { familyId: "core-anchor", review: "covered" },
  Spin: { familyId: "core-spin", review: "covered" },
  Carousel: { familyId: "core-carousel", review: "covered" },
  Slider: { familyId: "core-slider", review: "covered" },
  Rate: { familyId: "core-rate", review: "covered" },
  Segmented: { familyId: "core-segmented", review: "covered" },
  AutoComplete: { familyId: "core-autocomplete", review: "covered" },
  Collapse: { familyId: "core-collapse", review: "covered" },
  Popover: { familyId: "core-popover", review: "covered" },
  PopoverTrigger: { familyId: "core-popover", review: "needs-review" },
  PopoverContent: { familyId: "core-popover", review: "needs-review" },
  PopoverAnchor: { familyId: "core-popover", review: "needs-review" },
  Tooltip: { familyId: "core-tooltip", review: "covered" },
  TooltipTrigger: { familyId: "core-tooltip", review: "needs-review" },
  TooltipContent: { familyId: "core-tooltip", review: "needs-review" },
  TooltipProvider: { familyId: "core-tooltip", review: "needs-review" },
  DropdownMenu: { familyId: "core-dropdown", review: "covered" },
  DropdownMenuTrigger: { familyId: "core-dropdown", review: "needs-review" },
  DropdownMenuContent: { familyId: "core-dropdown", review: "needs-review" },
  DropdownMenuItem: { familyId: "core-dropdown", review: "needs-review" },
  DropdownMenuSeparator: { familyId: "core-dropdown", review: "needs-review" },
  DropdownMenuLabel: { familyId: "core-dropdown", review: "needs-review" },
  Cascader: { familyId: "core-cascader", review: "covered" },
  TreeSelect: { familyId: "core-tree-select", review: "covered" },
  Transfer: { familyId: "core-transfer", review: "covered" },
  Mentions: { familyId: "core-mentions", review: "covered" },
  Tree: { familyId: "core-tree", review: "covered" },
  Menu: { familyId: "core-menu", review: "covered" },
  QRCode: { familyId: "core-qrcode", review: "covered" },
  Watermark: { familyId: "core-watermark", review: "covered" },
  Affix: { familyId: "core-affix", review: "covered" },
  BackTop: { familyId: "core-back-top", review: "covered" },
  Splitter: { familyId: "core-splitter", review: "covered" },
  Layout: { familyId: "core-page-layout", review: "covered" },
  LayoutHeader: { familyId: "core-page-layout", review: "needs-review" },
  LayoutSider: { familyId: "core-page-layout", review: "needs-review" },
  LayoutContent: { familyId: "core-page-layout", review: "needs-review" },
  LayoutFooter: { familyId: "core-page-layout", review: "needs-review" },
  InputOTP: { familyId: "core-input-otp", review: "covered" },
  Popconfirm: { familyId: "core-popconfirm", review: "covered" },
  MessageProvider: { familyId: "core-message", review: "covered" },
  NotificationProvider: { familyId: "core-notification", review: "covered" },
  Tour: { familyId: "core-tour", review: "covered" },
} as const satisfies Record<string, CoreRuntimeFamilyCoverage>;
