import { createContext, useContext, type CSSProperties, type ReactNode } from "react";
import { cn } from "../lib/utils";
export interface UIConfig { componentSize?: "small"|"middle"|"large"; direction?: "ltr"|"rtl"; }
const ConfigContext = createContext<UIConfig>({});
export function ConfigProvider({ children, ...config }: UIConfig & { children: ReactNode }) { return <ConfigContext.Provider value={config}>{children}</ConfigContext.Provider>; }
export function useConfig() { return useContext(ConfigContext); }
export function App({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("min-h-full", className)}>{children}</div>; }
export function FloatButton({ icon, tooltip, onClick, href, className, style }: { icon?: ReactNode; tooltip?: ReactNode; onClick?: () => void; href?: string; className?: string; style?: CSSProperties }) { const content = <span aria-hidden={!tooltip}>{icon || "↑"}</span>; const props = { className: cn("fixed bottom-6 right-6 z-40 flex size-12 items-center justify-center rounded-full border bg-background shadow-lg hover:bg-accent", className), style, title: typeof tooltip === "string" ? tooltip : undefined, "aria-label": typeof tooltip === "string" ? tooltip : undefined }; return href ? <a {...props} href={href}>{content}</a> : <button {...props} type="button" onClick={onClick}>{content}</button>; }
export function Anchor({ items, offset = 0 }: { items: { key: string; title: ReactNode; href?: string }[]; offset?: number }) { return <nav aria-label="On this page" className="space-y-1">{items.map(item => <a key={item.key} href={item.href || `#${item.key}`} onClick={() => { if (offset) window.scrollTo({ top: offset, behavior: "smooth" }); }} className="block rounded px-2 py-1 text-sm text-muted-foreground hover:bg-accent hover:text-foreground">{item.title}</a>)}</nav>; }
export function Spin({ spinning = true, tip, children }: { spinning?: boolean; tip?: ReactNode; children?: ReactNode }) { return <div className="relative">{children}{spinning && <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 bg-background/70" role="status"><span className="size-5 animate-spin rounded-full border-2 border-primary border-r-transparent" />{tip && <span className="text-sm text-muted-foreground">{tip}</span>}</div>}</div>; }
