/** Gouno product-family components and page templates. */
export {
  AdminShell,
  NavigationGroup,
  navigationItemClass,
  type AdminShellProps,
  type NavigationGroupProps,
} from "./admin-shell";
export {
  Panel,
  PanelHeader,
  PanelBody,
  PlainSection,
  SectionHeading,
  EditorPanel,
  PageHeader,
  AdminPageState,
  AdminPage,
  ContentStack,
  ActionGroup,
  FilterBar,
  TableContainer,
  ButtonGroup,
  DefinitionList,
  DefinitionRow,
  ListStack,
  ListRow,
  type PanelProps,
  type PanelHeaderProps,
  type PanelBodyProps,
  type PlainSectionProps,
  type SectionHeadingProps,
  type EditorPanelProps,
  type PageHeaderProps,
  type AdminPageStateProps,
  type AdminPageProps,
  type ContentStackProps,
  type ActionGroupProps,
  type FilterBarProps,
  type TableContainerProps,
  type ButtonGroupProps,
  type DefinitionListProps,
  type DefinitionRowProps,
  type ListStackProps,
  type ListRowProps,
} from "./layout";
export {
  DashboardTemplate,
  ListPageTemplate,
  EditorWorkspaceTemplate,
  ResponsiveList,
  type DashboardTemplateProps,
  type ListPageTemplateProps,
  type EditorWorkspaceTemplateProps,
  type ResponsiveListProps,
} from "./templates";
export {
  StatusBadge,
  StatusIndicator,
  RiskBadge,
  type StatusBadgeProps,
  type StatusIndicatorProps,
  type RiskBadgeProps,
} from "./status-tags";
